# CPS ID: N/A, HC1703/HC1723S/HC1753S/HC1783S, 08/26/2021, IQ Qualification Level: Not Completed
# AUGENTIX HC18xx Initial attribute settings for OV4689 single sensor
# This '*.ini' file is used to fine tune picture quality.

#==================================#
#== Calibration algorithm enable ==#
#==================================#
# NOTE: if single sensor, only CAL0 valid
# ALSO SEE: MPI_setCalAttr

[CAL0]
cal_en = 1
dbc_en = 1
dcc_en = 1
lsc_en = 1

#==============================================#
#== Device black-level correction parameters ==#
#==============================================#
# NOTE: if single sensor, only DBC0 valid
# ALSO SEE: MPI_setDbcAttr
[DBC0]
mode = 2
dbc_level = 1016

#========================================#
#== Device color correction parameters ==#
#========================================#
# NOTE: if single sensor, only DCC0 valid
# ALSO SEE: MPI_setDccAttr
[DCC0]
gain[0] = 1100
gain[1] = 2400
gain[2] = 1700
gain[3] = 1100
offset_2s[0] = 0
offset_2s[1] = 0
offset_2s[2] = 0
offset_2s[3] = 0

#========================================#
#== Lens shading correction parameters ==#
#========================================#
# NOTE: if single sensor, only LSC0 valid
# ALSO SEE: MPI_setLscAttr
[LSC0]
origin = 4
x_trend_2s = 3368
y_trend_2s = 1928
x_curvature = 13569
y_curvature = 54810
tilt_2s = 0

#===============================================#
#== Digital Image Processing algorithm enable ==#
#===============================================#
# ALSO SEE: MPI_setDipAttr
[DIP]
is_dip_en = 1
is_ae_en = 1
is_iso_en = 1
is_awb_en = 1
is_csm_en = 1
is_te_en = 1
is_pta_en = 1
is_nr_en = 1
is_shp_en = 1
is_gamma_en = 1
is_dpc_en = 1
is_dms_en = 1
is_me_en = 0

#==============================#
#== Region Of Interest parameters ==#
#==============================#
# ALSO SEE: MPI_setRoiAttr
[ROI0]
luma_roi.sx = 256
luma_roi.sy = 341
luma_roi.ex = 768
luma_roi.ey = 853
awb_roi.sx = 0
awb_roi.sy = 0
awb_roi.ex = 1024
awb_roi.ey = 1024

#==============================#
#== Auto exposure parameters ==#
#==============================#
# ALSO SEE: MPI_setAeAttr
[AE]
#--- Target image brightness ---#
brightness = 7000

#--- AE strategy parameter---#
strategy.mode = 0
strategy.strength = 128

#--- Weight of ROI ---#
roi.luma_weight = 9
roi.awb_weight = 2

#--- Sensor gain range, isp gain range ---#
#sensor_gain_range : [32~510], isp_gain_range : [32~3200]
sys_gain_range.max = 1024
sys_gain_range.min = 48
sensor_gain_range.max = 510
sensor_gain_range.min = 32
isp_gain_range.max = 3200
isp_gain_range.min = 48

#--- Operation mode, target frame rate, system gain threshold ---#
fps_mode = 1
frame_rate = 30
slow_frame_rate = 15
gain_thr_up = 48
gain_thr_down = 49

#--- Speed, black_speed_bias, tolerance, black delay frame, white delay frame ---#
speed = 160
black_speed_bias = 128
tolerance = 1280
delay.white_delay_frame = 0
delay.black_delay_frame = 7

#--- Anti-flicker, enable, frequency, mode ---#
anti_flicker.enable = 1
anti_flicker.frequency = 60
anti_flicker.luma_delta = 4000

#--- Frame interval between two executions ---#
interval = 0

#--- Manual mode attribute ---#
manual.is_valid = 0
manual.enable.val = 0 ;b0: exp_value, b1: inttime, b2: sensor_gain, b3:isp_gain, b4: sys_gain
manual.exp_value = 3200
manual.inttime = 100
manual.isp_gain = 32
manual.sensor_gain = 32
manual.sys_gain = 32

#===================================#
#== Auto white balance parameters ==#
#===================================#
# ALSO SEE: MPI_setAwbAttr
[AWB]
#--- Convergence speed ---#
speed = 64

#--- Boundary of color temperature ---#
low_k = 2800
high_k = 6500

#--- Extra R, G, B channel gain multiplied to result ---#
r_extra_gain = 128
g_extra_gain = 128
b_extra_gain = 128

#--- Maximal luma gain multiplied to result ---#
max_lum_gain = 90

#--- Weight for white, gray areas and channel average ---#
wht_weight = 96
gwd_weight = 64

#--- tolerance for correlated color temperature ---#
color_tolerance = 64

#--- white area density and threshold for over exposure ---#
wht_density = 0
over_exp_th = 13000

#--- Color matrix information ---#
k_table_valid_size = 4
k_table[0].k = 2800
bias_table[0].k = 2800
bias_table[0].color_tolerance_bias = 0
bias_table[0].wht_weight_bias = 0
bias_table[0].gwd_weight_bias = 0
bias_table[0].r_extra_gain_bias = 0
bias_table[0].g_extra_gain_bias = 0
bias_table[0].b_extra_gain_bias = 0
k_table[0].gain[0] = 256
k_table[0].gain[1] = 144
k_table[0].gain[2] = 446
k_table[0].gain[3] = 255
k_table[0].matrix[0] = 3529
k_table[0].matrix[1] = -801
k_table[0].matrix[2] = -679
k_table[0].matrix[3] = -1337
k_table[0].matrix[4] = 4019
k_table[0].matrix[5] = -634
k_table[0].matrix[6] = 132
k_table[0].matrix[7] = -3587
k_table[0].matrix[8] = 5502
k_table[1].k = 4000
bias_table[1].k = 4000
bias_table[1].color_tolerance_bias = 0
bias_table[1].wht_weight_bias = 0
bias_table[1].gwd_weight_bias = 0
bias_table[1].r_extra_gain_bias = 0
bias_table[1].g_extra_gain_bias = 0
bias_table[1].b_extra_gain_bias = 0
k_table[1].gain[0] = 255
k_table[1].gain[1] = 211
k_table[1].gain[2] = 355
k_table[1].gain[3] = 256
k_table[1].matrix[0] = 4162
k_table[1].matrix[1] = -1984
k_table[1].matrix[2] = -130
k_table[1].matrix[3] = -875
k_table[1].matrix[4] = 3175
k_table[1].matrix[5] = -252
k_table[1].matrix[6] = 330
k_table[1].matrix[7] = -2404
k_table[1].matrix[8] = 4122
k_table[2].k = 4800
bias_table[2].k = 4800
bias_table[2].color_tolerance_bias = 0
bias_table[2].wht_weight_bias = 0
bias_table[2].gwd_weight_bias = 0
bias_table[2].r_extra_gain_bias = 0
bias_table[2].g_extra_gain_bias = 0
bias_table[2].b_extra_gain_bias = 0
k_table[2].gain[0] = 256
k_table[2].gain[1] = 227
k_table[2].gain[2] = 310
k_table[2].gain[3] = 255
k_table[2].matrix[0] = 3825
k_table[2].matrix[1] = -1409
k_table[2].matrix[2] = -368
k_table[2].matrix[3] = -1059
k_table[2].matrix[4] = 3831
k_table[2].matrix[5] = -724
k_table[2].matrix[6] = 53
k_table[2].matrix[7] = -2353
k_table[2].matrix[8] = 4347
k_table[3].k = 6500
bias_table[3].k = 6500
bias_table[3].color_tolerance_bias = 0
bias_table[3].wht_weight_bias = 0
bias_table[3].gwd_weight_bias = 0
bias_table[3].r_extra_gain_bias = 0
bias_table[3].g_extra_gain_bias = 0
bias_table[3].b_extra_gain_bias = 0
k_table[3].gain[0] = 256
k_table[3].gain[1] = 252
k_table[3].gain[2] = 252
k_table[3].gain[3] = 255
k_table[3].matrix[0] = 3504
k_table[3].matrix[1] = -1535
k_table[3].matrix[2] = 79
k_table[3].matrix[3] = -489
k_table[3].matrix[4] = 3198
k_table[3].matrix[5] = -660
k_table[3].matrix[6] = 347
k_table[3].matrix[7] = -2207
k_table[3].matrix[8] = 3907
k_table[4].k = 0
bias_table[4].k = 0
bias_table[4].color_tolerance_bias = 0
bias_table[4].wht_weight_bias = 0
bias_table[4].gwd_weight_bias = 0
bias_table[4].r_extra_gain_bias = 0
bias_table[4].g_extra_gain_bias = 0
bias_table[4].b_extra_gain_bias = 0
k_table[4].gain[0] = 256
k_table[4].gain[1] = 256
k_table[4].gain[2] = 256
k_table[4].gain[3] = 256
k_table[4].matrix[0] = 2048
k_table[4].matrix[1] = 0
k_table[4].matrix[2] = 0
k_table[4].matrix[3] = 0
k_table[4].matrix[4] = 2048
k_table[4].matrix[5] = 0
k_table[4].matrix[6] = 0
k_table[4].matrix[7] = 0
k_table[4].matrix[8] = 2048
k_table[5].k = 0
bias_table[5].k = 0
bias_table[5].color_tolerance_bias = 0
bias_table[5].wht_weight_bias = 0
bias_table[5].gwd_weight_bias = 0
bias_table[5].r_extra_gain_bias = 0
bias_table[5].g_extra_gain_bias = 0
bias_table[5].b_extra_gain_bias = 0
k_table[5].gain[0] = 256
k_table[5].gain[1] = 256
k_table[5].gain[2] = 256
k_table[5].gain[3] = 256
k_table[5].matrix[0] = 2048
k_table[5].matrix[1] = 0
k_table[5].matrix[2] = 0
k_table[5].matrix[3] = 0
k_table[5].matrix[4] = 2048
k_table[5].matrix[5] = 0
k_table[5].matrix[6] = 0
k_table[5].matrix[7] = 0
k_table[5].matrix[8] = 2048
k_table[6].k = 0
bias_table[6].k = 0
bias_table[6].color_tolerance_bias = 0
bias_table[6].wht_weight_bias = 0
bias_table[6].gwd_weight_bias = 0
bias_table[6].r_extra_gain_bias = 0
bias_table[6].g_extra_gain_bias = 0
bias_table[6].b_extra_gain_bias = 0
k_table[6].gain[0] = 256
k_table[6].gain[1] = 256
k_table[6].gain[2] = 256
k_table[6].gain[3] = 256
k_table[6].matrix[0] = 2048
k_table[6].matrix[1] = 0
k_table[6].matrix[2] = 0
k_table[6].matrix[3] = 0
k_table[6].matrix[4] = 2048
k_table[6].matrix[5] = 0
k_table[6].matrix[6] = 0
k_table[6].matrix[7] = 0
k_table[6].matrix[8] = 2048
k_table[7].k = 0
bias_table[7].k = 0
bias_table[7].color_tolerance_bias = 0
bias_table[7].wht_weight_bias = 0
bias_table[7].gwd_weight_bias = 0
bias_table[7].r_extra_gain_bias = 0
bias_table[7].g_extra_gain_bias = 0
bias_table[7].b_extra_gain_bias = 0
k_table[7].gain[0] = 256
k_table[7].gain[1] = 256
k_table[7].gain[2] = 256
k_table[7].gain[3] = 256
k_table[7].matrix[0] = 2048
k_table[7].matrix[1] = 0
k_table[7].matrix[2] = 0
k_table[7].matrix[3] = 0
k_table[7].matrix[4] = 2048
k_table[7].matrix[5] = 0
k_table[7].matrix[6] = 0
k_table[7].matrix[7] = 0
k_table[7].matrix[8] = 2048

#--- Color delta information ---#
delta_table[0].gain[0] = 0
delta_table[0].gain[1] = 0
delta_table[0].gain[2] = 0
delta_table[0].gain[3] = 0
delta_table[1].gain[0] = 0
delta_table[1].gain[1] = 0
delta_table[1].gain[2] = 0
delta_table[1].gain[3] = 0
delta_table[2].gain[0] = 0
delta_table[2].gain[1] = 0
delta_table[2].gain[2] = 0
delta_table[2].gain[3] = 0
delta_table[3].gain[0] = 0
delta_table[3].gain[1] = 0
delta_table[3].gain[2] = 0
delta_table[3].gain[3] = 0
delta_table[4].gain[0] = 0
delta_table[4].gain[1] = 0
delta_table[4].gain[2] = 0
delta_table[4].gain[3] = 0
delta_table[5].gain[0] = 0
delta_table[5].gain[1] = 0
delta_table[5].gain[2] = 0
delta_table[5].gain[3] = 0
delta_table[6].gain[0] = 0
delta_table[6].gain[1] = 0
delta_table[6].gain[2] = 0
delta_table[6].gain[3] = 0
delta_table[7].gain[0] = 0
delta_table[7].gain[1] = 0
delta_table[7].gain[2] = 0
delta_table[7].gain[3] = 0
#=====================================#
#== Post tone adjustment parameters ==#
#=====================================#
# ALSO SEE: MPI_setPtaAttr
[PTA]
mode        = 0   ;Operation mode, 0: normal, 1: manual
brightness  = 128 ;The strength to brighten image.
contrast    = 128 ;The curvature of curve
break_point = 64  ;The breakpoint of contrast curve
pta_auto.tone[0] =  1024 ;iso = 100
pta_auto.tone[1] =  1024 ;iso = 200
pta_auto.tone[2] =  1024 ;iso = 400
pta_auto.tone[3] =  1024 ;iso = 800
pta_auto.tone[4] =  1024 ;iso = 1600
pta_auto.tone[5] =  1024 ;iso = 3200
pta_auto.tone[6] =  1024 ;iso = 6400
pta_auto.tone[7] =  1024 ;iso = 12800
pta_auto.tone[8] =  1024 ;iso = 51200
pta_auto.tone[9] =  1024 ;iso = 102400
pta_auto.tone[10] = 1024 ;iso = 204800
# PTA manual curve
pta_manual.curve[0] =    0
pta_manual.curve[1] =    8
pta_manual.curve[2] =   24
pta_manual.curve[3] =   51
pta_manual.curve[4] =   85
pta_manual.curve[5] =  124
pta_manual.curve[6] =  167
pta_manual.curve[7] =  213
pta_manual.curve[8] =  260
pta_manual.curve[9] =  308
pta_manual.curve[10] = 355
pta_manual.curve[11] = 401
pta_manual.curve[12] = 446
pta_manual.curve[13] = 489
pta_manual.curve[14] = 529
pta_manual.curve[15] = 568
pta_manual.curve[16] = 604
pta_manual.curve[17] = 638
pta_manual.curve[18] = 670
pta_manual.curve[19] = 699
pta_manual.curve[20] = 728
pta_manual.curve[21] = 754
pta_manual.curve[22] = 780
pta_manual.curve[23] = 805
pta_manual.curve[24] = 829
pta_manual.curve[25] = 853
pta_manual.curve[26] = 876
pta_manual.curve[27] = 900
pta_manual.curve[28] = 924
pta_manual.curve[29] = 949
pta_manual.curve[30] = 974
pta_manual.curve[31] = 999
pta_manual.curve[32] = 1024

#============================================#
#== Color saturation management parameters ==#
#============================================#
#NOTE: Saturation level, only valid at manual mode
#ALSO SEE: MPI_setCsmAttr
[CSM]
bw_en = 0                     ;Black and white enable
mode = 0                      ;Operation mode, 0: auto, 2: manual
csm_auto.saturation[0] = 160  ;iso = 100
csm_auto.saturation[1] = 150  ;iso = 200
csm_auto.saturation[2] = 140  ;iso = 400
csm_auto.saturation[3] = 128  ;iso = 800
csm_auto.saturation[4] = 85   ;iso = 1600
csm_auto.saturation[5] = 85   ;iso = 3200
csm_auto.saturation[6] = 85   ;iso = 6400
csm_auto.saturation[7] = 85   ;iso = 12800
csm_auto.saturation[8] = 85   ;iso = 25600
csm_auto.saturation[9] = 85   ;iso = 51200
csm_auto.saturation[10] = 85   ;iso = 102400
csm_manual.saturation = 128   ;Saturation level

#===========================#
#== Sharpening parameters ==#
#===========================#
#NOTE: Sharpness strength, only valid at manual mode
#ALSO SEE: MPI_setShpAttr
[SHP]
mode = 0                     ;Operation mode, 0: auto, 2: manual
shp_auto.sharpness[0] = 191  ;iso = 100
shp_auto.sharpness[1] =  75  ;iso = 200
shp_auto.sharpness[2] =  45  ;iso = 400
shp_auto.sharpness[3] =   0  ;iso = 800
shp_auto.sharpness[4] =   0  ;iso = 1600
shp_auto.sharpness[5] =   0  ;iso = 3200
shp_auto.sharpness[6] =   0  ;iso = 6400
shp_auto.sharpness[7] =   0  ;iso = 12800
shp_auto.sharpness[8] =   0  ;iso = 25600
shp_auto.sharpness[9] =   0  ;iso = 51200
shp_auto.sharpness[10] =  0  ;iso = 102400
shp_manual.sharpness = 128   ;Sharpness strength

#================================#
#== Noise reduction parameters ==#
#================================#
#NOTE: Noise reduction strength, only valid at manual mode
#ALSO SEE: MPI_setNrAttr
[NR]
mode = 0                     ;Operation mode, 0: auto, 2: manual
nr_auto.y_level_3d[0] = 113  ;iso = 100
nr_auto.y_level_3d[1] = 137  ;iso = 200
nr_auto.y_level_3d[2] = 143  ;iso = 400
nr_auto.y_level_3d[3] = 150  ;iso = 800
nr_auto.y_level_3d[4] = 156  ;iso = 1600
nr_auto.y_level_3d[5] = 162  ;iso = 3200
nr_auto.y_level_3d[6] = 168  ;iso = 6400
nr_auto.y_level_3d[7] = 175  ;iso = 12800
nr_auto.y_level_3d[8] = 181  ;iso = 25600
nr_auto.y_level_3d[9] = 187  ;iso = 51200
nr_auto.y_level_3d[10] = 193 ;iso = 102400

nr_auto.c_level_3d[0] = 49   ;iso = 100
nr_auto.c_level_3d[1] = 75   ;iso = 200
nr_auto.c_level_3d[2] = 81   ;iso = 400
nr_auto.c_level_3d[3] = 87   ;iso = 800
nr_auto.c_level_3d[4] = 93   ;iso = 1600
nr_auto.c_level_3d[5] = 100   ;iso = 3200
nr_auto.c_level_3d[6] = 106  ;iso = 6400
nr_auto.c_level_3d[7] = 113  ;iso = 12800
nr_auto.c_level_3d[8] = 119  ;iso = 25600
nr_auto.c_level_3d[9] = 125  ;iso = 51200
nr_auto.c_level_3d[10] = 131 ;iso = 102400

nr_auto.y_level_2d[0] = 100  ;iso = 100
nr_auto.y_level_2d[1] = 100  ;iso = 200
nr_auto.y_level_2d[2] = 100  ;iso = 400
nr_auto.y_level_2d[3] = 100  ;iso = 800
nr_auto.y_level_2d[4] = 100  ;iso = 1600
nr_auto.y_level_2d[5] = 100  ;iso = 3200
nr_auto.y_level_2d[6] = 100  ;iso = 6400
nr_auto.y_level_2d[7] = 100  ;iso = 12800
nr_auto.y_level_2d[8] = 100  ;iso = 25600
nr_auto.y_level_2d[9] = 100  ;iso = 51200
nr_auto.y_level_2d[10] = 100 ;iso = 102400

nr_auto.c_level_2d[0] = 150  ;iso = 100
nr_auto.c_level_2d[1] = 150  ;iso = 200
nr_auto.c_level_2d[2] = 150  ;iso = 400
nr_auto.c_level_2d[3] = 150  ;iso = 800
nr_auto.c_level_2d[4] = 150  ;iso = 1600
nr_auto.c_level_2d[5] = 150  ;iso = 3200
nr_auto.c_level_2d[6] = 150  ;iso = 6400
nr_auto.c_level_2d[7] = 150  ;iso = 12800
nr_auto.c_level_2d[8] = 150  ;iso = 25600
nr_auto.c_level_2d[9] = 150  ;iso = 51200
nr_auto.c_level_2d[10] = 150 ;iso = 102400

nr_manual.y_level_3d = 128   ;Noise reduction 3d luma strength
nr_manual.c_level_3d = 128    ;Noise reduction 3d chroma strength
nr_manual.y_level_2d = 128   ;Noise reduction 2d luma strength
nr_manual.c_level_2d = 128   ;Noise reduction 2d chroma strength

motion_comp = 2              ;mc ratio (BASE_DYN) (0~31)
trail_suppress = 0           ;trail suppress strength level (0~16)
ghost_remove = 0             ;ghost removes trength level
ma_y_strength = 26           ;max 3d ma luma strength(0~31)
mc_y_strength = 30           ;max 3d mc luma strength(0~31)
ma_c_strength = 24           ;max 3d ma chroma strength(0~31)
ratio_3d = 4                 ;strength level (0~4)(0:all 2d , 4:Mostly 3d)
mc_y_level_offset = 0        ;mc luma level offset(-255~255)
me_frame_fallback_en = 0     ;enable me frame fallback

#======================#
#== Gamma parameters ==#
#======================#
#ALSO SEE: MPI_setGammaAttr
[GAMMA]
mode = 0          ;Operation mode, 0: BT.709, 1: Gamma2.2

#=================================#
#== Tone enhancement parameters ==#
#=================================#
#NOTE: WDR mode only valid at single sensor
#ALSO SEE: MPI_setTeAttr
[TE]
mode = 0        ;Operation mode, 0: normal, 1: wdr
# Normal mode
te_normal.curve[0] = 0
te_normal.curve[1] = 25
te_normal.curve[2] = 57
te_normal.curve[3] = 91
te_normal.curve[4] = 133
te_normal.curve[5] = 175
te_normal.curve[6] = 215
te_normal.curve[7] = 261
te_normal.curve[8] = 308
te_normal.curve[9] = 402
te_normal.curve[10] =496
te_normal.curve[11] =596
te_normal.curve[12] =700
te_normal.curve[13] =809
te_normal.curve[14] =920
te_normal.curve[15] =1035
te_normal.curve[16] =1153
te_normal.curve[17] =1273
te_normal.curve[18] =1395
te_normal.curve[19] =1519
te_normal.curve[20] =1645
te_normal.curve[21] =1773
te_normal.curve[22] =1903
te_normal.curve[23] =2033
te_normal.curve[24] =2165
te_normal.curve[25] =2431
te_normal.curve[26] =2701
te_normal.curve[27] =2975
te_normal.curve[28] =3253
te_normal.curve[29] =3533
te_normal.curve[30] =3815
te_normal.curve[31] =4099
te_normal.curve[32] =4387
te_normal.curve[33] =4677
te_normal.curve[34] =4968
te_normal.curve[35] =5261
te_normal.curve[36] =5557
te_normal.curve[37] =5855
te_normal.curve[38] =6154
te_normal.curve[39] =6455
te_normal.curve[40] =6757
te_normal.curve[41] =7365
te_normal.curve[42] =7978
te_normal.curve[43] =8593
te_normal.curve[44] =9209
te_normal.curve[45] =9822
te_normal.curve[46] =10431
te_normal.curve[47] =11034
te_normal.curve[48] =11626
te_normal.curve[49] =12204
te_normal.curve[50] =12765
te_normal.curve[51] =13305
te_normal.curve[52] =13820
te_normal.curve[53] =14306
te_normal.curve[54] =14759
te_normal.curve[55] =15175
te_normal.curve[56] =15549
te_normal.curve[57] =15877
te_normal.curve[58] =16157
te_normal.curve[59] =16384
# WDR mode
te_wdr.brightness = 5658   ;Brightness strength
te_wdr.strength = 512      ;Content adaptive enhancement strength
te_wdr.saliency = 512      ;Non-linear enhancement for dynamic range reallocation
te_wdr.noise_cstr[0] = 64  ;Noise constraint, iso = 100
te_wdr.noise_cstr[1] = 128  ;Noise constraint, iso = 200
te_wdr.noise_cstr[2] = 256  ;Noise constraint, iso = 400
te_wdr.noise_cstr[3] = 512  ;Noise constraint, iso = 800
te_wdr.noise_cstr[4] = 640  ;Noise constraint, iso = 1600
te_wdr.noise_cstr[5] = 768  ;Noise constraint, iso = 3200
te_wdr.noise_cstr[6] = 896  ;Noise constraint, iso = 6400
te_wdr.noise_cstr[7] = 1024  ;Noise constraint, iso = 12800
te_wdr.noise_cstr[8] = 1024  ;Noise constraint, iso = 25600
te_wdr.noise_cstr[9] = 1024  ;Noise constraint, iso = 51200
te_wdr.noise_cstr[10] = 1024 ;Noise constraint, iso = 102400
te_wdr.iso_weight = 128    ;Weighting adjustment of ISO calculation
te_wdr.dark_enhance = 16   ;Dark region enhancing strength
te_wdr.iso_max = 3200      ;Constraint maximal ISO (1x: 100)
te_wdr.interval = 0        ;Interval between two executions
te_wdr.precision = 2       ;Operation on 0: 15bins, 1: 30bins, 2: 60bins