#define AGTX_RTC_CTRL       0x00
#define AGTX_RTC_STATE      0x04
#define AGTX_RTC_RST_STATE  0x08
#define AGTX_IRQ_CLEAR      0x0C
#define AGTX_IRQ_MASK       0x10
#define AGTX_IRQ_STATUS     0x14
#define AGTX_TIME_WRITE     0x18
#define AGTX_TIME_READ      0x1C
#define AGTX_ALARM_CPU      0x20
#define AGTX_ALARM_PMU      0x24

/* RTC_CTRL (0x00) */
#define RUN_STOP_OFFSET 0
#define READ_OFFSET 8
#define WRITE_OFFSET 16
/* RTC_STATE (0x04) */
#define COUNTING_BUSY_OFFSET 0
#define READ_DONE_OFFSET 8
#define WRITE_DONE_OFFSET 16

#define RTC_NOT_COUNTING	0
#define RTC_COUNTING		1
#define RTC_READING		0
#define RTC_NOT_READING		1
#define RTC_WRITING		0
#define RTC_NOT_WRITING		1
/* RTC_RST_STATE (0x08) */
#define RST_STATE_OFFSET 0
/* IRQ_CLEAR (0x0C) */
#define IRQ_CLEAR_ALARM_CPU_OFFSET 0
#define IRQ_CLEAR_ALARM_PMU_OFFSET 8
/* IRQ_MASK (0x10) */
#define IRQ_MASK_ALARM_CPU_OFFSET 0
#define IRQ_MASK_ALARM_PMU_OFFSET 8
/* IRQ_STATUS (0x14) */
#define STATUS_MATCH_ALARM_CPU_OFFSET 0
#define STATUS_MATCH_ALARM_PMU_OFFSET 8
/* TIME_WRITE (0x18) */
#define TIME_SEC_WRITE_OFFSET 0
#define TIME_MIN_WRITE_OFFSET 6
#define TIME_HOUR_WRITE_OFFSET 12
#define TIME_DAY_WRITE_OFFSET 17
/* TIME_READ (0x1C) */
#define TIME_SEC_READ_OFFSET 0
#define TIME_MIN_READ_OFFSET 6
#define TIME_HOUR_READ_OFFSET 12
#define TIME_DAY_READ_OFFSET 17
/* ALARM_CPU (0x20) */
#define ALARM_CPU_SEC_TH_OFFSET 0
#define ALARM_CPU_MIN_TH_OFFSET 6
#define ALARM_CPU_HOUR_TH_OFFSET 12
#define ALARM_CPU_DAY_TH_OFFSET 17
/* ALARM_PMU (0x24) */
#define ALARM_PMU_SEC_TH_OFFSET 0
#define ALARM_PMU_MIN_TH_OFFSET 6
#define ALARM_PMU_HOUR_TH_OFFSET 12
#define ALARM_PMU_DAY_TH_OFFSET 17

#define RTC_RST_MAGIC     0xb0075ce5
#define AGTX_RTC_TIMEOUT_USEC 1000000

#define SEC_MASK   GENMASK(5, 0)
#define MIN_MASK   GENMASK(5, 0)
#define HOUR_MASK  GENMASK(4, 0)
#define DAY_MASK   GENMASK(14, 0)

/* PC.CK.DEF_APB_0 Offset */
#define APB0_DIV_OFFSET 1

/* PC.SYSCFG.PMU_EN Offset */
#define PMU_APB_READ_OFFSET 0
#define PMU_APB_WRITE_OFFSET 8
#define PMU_APB_IRQ_OFFSET 16
#define PMU_APB_GPIO_I_OFFSET 24
