#include "sensor_comm.h"

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdint.h>
#include <inttypes.h>

extern void sensor_power_up();
static void write_head();
static void write_end();

int i2c_idx = 0;
int g_gpio_export_list[128];
char g_sensor_name[32];
FILE *g_file_ptr = NULL;

int main(int argc, char *argv[])
{
	memset(g_gpio_export_list, 0, sizeof(g_gpio_export_list));
	memset(g_sensor_name, 0, sizeof(g_sensor_name));

	if (argc < 3) {
		fprintf(stderr, "Usage: %s sensor filename\n", argv[0]);
		return 1;
	}

	strncpy(g_sensor_name, argv[1], 31);
	for (int i = 0; g_sensor_name[i]; i++) {
		g_sensor_name[i] = toupper(g_sensor_name[i]);
	}

	g_file_ptr = fopen(argv[2], "w");
	if (g_file_ptr == NULL) {
		fprintf(stderr, "Unable to create file '%s'.\n", argv[2]);
		return 1;
	}

	write_head();
	sensor_power_up();
	write_end();
	fclose(g_file_ptr);

	return 0;
}

static void write_head()
{
	fprintf(g_file_ptr, "#!/bin/sh\n");
	fprintf(g_file_ptr, "\n");
	fprintf(g_file_ptr, "# auto_sensor_power_on.sh: Power on script to power up the sensor on DUT.\n");
	fprintf(g_file_ptr, "# This file is generated by codegen, DO NOT COMMIT THIS FILE.\n");
	fprintf(g_file_ptr, "\n");
	fprintf(g_file_ptr, "SENSOR=%s\n", g_sensor_name);
	fprintf(g_file_ptr, "\n");
	fprintf(g_file_ptr, "echo \"Start to power on $SENSOR\"\n");
	fprintf(g_file_ptr, "\n");
}

static void write_end()
{
	for (int i = 0; i < 128; i++) {
		if (g_gpio_export_list[i]) {
			fprintf(g_file_ptr, "echo %d > /sys/class/gpio/unexport\n", i);
			g_gpio_export_list[i] = 0;
		}
	}
	fprintf(g_file_ptr, "\n");
	fprintf(g_file_ptr, "echo \"Power on $SENSOR done\"\n");
	fprintf(g_file_ptr, "\n");
}

void gpio_set_value(int gpio_id, int level)
{
	if (level) {
		level = 1;
	}
	fprintf(g_file_ptr, "echo %d > /sys/class/gpio/gpio%d/value\n", level, gpio_id);
	fprintf(g_file_ptr, "\n");
}

void gpio_direction_output(int gpio_id, int level)
{
	if (gpio_id < 0 || gpio_id > 80) {
		fprintf(stderr, "Warning: Unsupported GPIO %d in power up sequence.\n", gpio_id);
		return;
	}

	if (!g_gpio_export_list[gpio_id]) {
		fprintf(g_file_ptr, "echo %d > /sys/class/gpio/export\n", gpio_id);
		fprintf(g_file_ptr, "echo out > /sys/class/gpio/gpio%d/direction\n", gpio_id);
		fprintf(g_file_ptr, "\n");
		g_gpio_export_list[gpio_id] = 1;
	}
	gpio_set_value(gpio_id, level);
}

void mdelay(unsigned long msec)
{
	udelay(msec * 1000);
}

void udelay(unsigned long usec)
{
	fprintf(g_file_ptr, "usleep %lu\n", usec);
	fprintf(g_file_ptr, "\n");
}

int i2c_write_seq(int slave_addr, const SensCmd *cmd, int num_of_write, int addr_len, int data_len)
{
	if (num_of_write < 1) {
		return 1;
	}

	for (int i = 0; i < num_of_write; i++) {
		if (addr_len == 1 && data_len == 1) {
			fprintf(g_file_ptr, "i2crw -Bb -D%d -S0x%02x 0x%02x 0x%02x\n", i2c_idx, slave_addr,
			        (uint8_t)cmd[i].reg, (uint8_t)cmd[i].val);
		} else if (addr_len == 2 && data_len == 1) {
			fprintf(g_file_ptr, "i2crw -Wb -D%d -S0x%02x 0x%04x 0x%02x\n", i2c_idx, slave_addr, cmd[i].reg,
			        (uint8_t)cmd[i].val);
		} else if (addr_len == 2 && data_len == 2) {
			fprintf(g_file_ptr, "i2crw -Ww -D%d -S0x%02x 0x%04x 0x%04x\n", i2c_idx, slave_addr, cmd[i].reg,
			        cmd[i].val);
		}
	}
	fprintf(g_file_ptr, "\n");

	return 0;
}

int i2c_set_bus_num(unsigned int bus)
{
	i2c_idx = bus;
	return 0;
}
