# Minimal machine used only for SDK/toolchain generation (no images/kernel)

# Pull in Cortex-A7 tunes
require conf/machine/include/tune-cortexa7.inc

#Hard-float + Thumb + NEON/VFPv4
DEFAULTTUNE = "cortexa7thf-neon-vfpv4"
TUNE_CCARGS_tune-cortexa7thf-neon-vfpv4 = " -march=armv7ve -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard"
QTI_IPCAM_FLOATABI = "hard"

# Make it clear we are not building a full image
IMAGE_FSTYPES = ""
KERNEL_IMAGETYPE = ""

ARM_INSTRUCTION_SET = "thumb"

