require conf/machine/qti-ipcam-cortexa7.conf

# ---- Pure soft-float policy ----
DEFAULTTUNE = "cortexa7t"

# Add call convention to pure soft
TUNE_FEATURES_remove = "callconvention-hard callconvention-softfp"
TUNE_FEATURES_append = " callconvention-soft"

# Remove vfp to make TARGET_FPU to soft
TUNE_FEATURES_remove = "vfp"

# Clear -mfpu=vfp / softfp
TUNE_CCARGS_remove = " -mfpu=vfp -mfloat-abi=softfp -msoft-float"
TUNE_CCARGS_append = " -mfloat-abi=soft -mfpu=auto -msoft-float"

#Add cortexa7t2 to PACKAGE_EXTRA_ARCHS
PACKAGE_EXTRA_ARCHS_append = " cortexa7t2"

QTI_IPCAM_FLOATABI = "soft"

