#!/bin/sh
export PACKAGE_PATH=`pwd`
export EXTERN_PROGRAM_PATH=${PACKAGE_PATH}
export PATH=${PACKAGE_PATH}:${EXTERN_PROGRAM_PATH}:${PATH}
export LD_LIBRARY_PATH=${EXTERN_PROGRAM_PATH}:${LD_LIBRARY_PATH}
export SHELL=${EXTERN_PROGRAM_PATH}/sh:${SHELL}

chmod 755 *