#!/bin/sh

IS_FASTBOOT=y
IS_SECURE_BOOT=y

panic_shell() {
	echo "[initramfs] ERROR: $1"
	halt -f
}

# mount /proc, /sys, /dev
mkdir -p /proc /sys /dev
mount -t proc proc /proc || panic_shell "mount /proc failed"
mount -t sysfs sysfs /sys || panic_shell "mount /sys failed"
if ! mount -t devtmpfs devtmpfs /dev 2>/dev/null; then
	mkdir -p /dev
	[ -c /dev/console ] || mknod /dev/console c 5 1
	[ -c /dev/null ]    || mknod /dev/null    c 1 3
fi

# mount /run, /tmp
mkdir -p /run /tmp
mount -t tmpfs -o mode=0755,nosuid,nodev tmpfs /run || panic_shell "mount /run failed"
mount -t tmpfs -o mode=1777 tmpfs /tmp || panic_shell "mount /tmp failed"

# start fastboot video if present
if [ "$IS_FASTBOOT" = "y" ]; then
	export LD_LIBRARY_PATH=/system/lib
	. /etc/fastboot_video
fi

# mount the real root
mkdir -p /root
ROOT_DEV=$(cat /proc/cmdline | awk 'BEGIN{FS="root="}{sub(/ .*/,"",$2);print $2}')
if [ "$IS_SECURE_BOOT" = "y" ]; then
	# create the mapper device and then mount it for Secure Boot method A
	VERITY_MTDID=$ROOT_DEV
	MAPPER_NAME=rootfs
	MAPPER_DEV=/dev/mapper/${MAPPER_NAME}
	ROOTHASH=$(cat /proc/cmdline | awk 'BEGIN{FS="roothash="}{sub(/ .*/,"",$2);print $2}')
	HASH_OFFSET=$(cat /proc/cmdline | awk 'BEGIN{FS="hash_offset="}{sub(/ .*/,"",$2);print $2}')
	veritysetup create ${MAPPER_NAME} --hash-offset ${HASH_OFFSET} ${VERITY_MTDID} ${VERITY_MTDID} ${ROOTHASH} || \
		panic_shell "failed to create the mapper device for rootfs, force system halt !!!"
    # mount the mapper device
	mount -o ro ${MAPPER_DEV} /root || panic_shell "mount mapper device for rootfs failed"
else
    # mount the MTD block device
	mount -o ro ${ROOT_DEV} /root || panic_shell "mount mtd block for rootfs failed"
fi

# move /dev, /run, /tmp, /sys to real root
mkdir -p /root/dev /root/run /root/tmp /root/sys /root/proc
mount --move /dev  /root/dev  || panic_shell "move /dev failed"
mount --move /run  /root/run  || panic_shell "move /run failed"
mount --move /tmp  /root/tmp  || panic_shell "move /tmp failed"
mount --move /sys  /root/sys  || panic_shell "move /sys failed"


# Keep /proc in initramfs (mpi_stream needs /proc/mounts).
# Mount a fresh /proc in rootfs.
mount -t proc proc /root/proc || panic_shell "mount /proc in real rootfs failed"


# Initramfs /mnt/sdcard for mpi_stream.
# S01fastboot bind-mounts real SD later.
mkdir -p /mnt/sdcard

# # cleanup mounting points
# umount /proc || panic_shell "umount /proc failed"
# umount /sys  || panic_shell "umount /sys failed"

# switch to real root
exec switch_root -c /dev/console /root /sbin/init
