#include "webs.h"
#include "AntsWebCommon.h"
#include "web_inter_api.h"
#include "upload.h"

/********************************* Defines ************************************/

#define WEBS_ENCODE_HTML    0x1                 /* Bit setting in charMatch[] */

/************************************ Locals **********************************/


static Webs         **webs;                     /* Open connection list head */
static WebsHash     websMime;                   /* Set of mime types */
static int          websMax;                    /* List size */
static char         websHost[ME_MAX_IP];        /* Host name for the server */
static char         websIpAddr[ME_MAX_IP];      /* IP address for the server */
static char         *websHostUrl = "::";        /* URL to access server */
static char         *websIpAddrUrl = NULL;      /* URL to access server */
WebsHash 		sessions = -1;
static int      	sessionCount = 0;
#if 0
static int      	pruneId;
#endif

extern int  upload_file_save_as(int content_length, Webs *wp);

/*
    Character escape/descape matching codes. Generated by charGen.
 */
static uchar charMatch[256] = {
    0x00,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3e,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x0c,0x3f,0x28,0x2a,0x3c,0x2b,0x0f,0x0e,0x0e,0x0e,0x28,0x28,0x00,0x00,0x28,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x28,0x2a,0x3f,0x28,0x3f,0x2a,
    0x28,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x3a,0x3e,0x3a,0x3e,0x00,
    0x3e,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x3e,0x3e,0x3e,0x02,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,
    0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c,0x3c
};

/*
    Addd entries to the MimeList as required for your content
 */
static WebsMime websMimeList[] = {
    { "application/java", ".class" },
    { "application/java", ".jar" },
    { "text/html", ".asp" },
    { "text/html", ".htm" },
    { "text/html", ".html" },
    { "text/xml", ".xml" },
    { "image/gif", ".gif" },
    { "image/jpeg", ".jpg" },
    { "image/png", ".png" },
    { "image/vnd.microsoft.icon", ".ico" },
    { "text/css", ".css" },
    { "text/plain", ".txt" },
    { "application/x-javascript", ".js" },
    { "application/x-shockwave-flash", ".swf" },

    { "application/binary", ".exe" },
    { "application/compress", ".z" },
    { "application/gzip", ".gz" },
    { "application/octet-stream", ".bin" },
    { "application/oda", ".oda" },
    { "application/pdf", ".pdf" },
    { "application/postscript", ".ai" },
    { "application/postscript", ".eps" },
    { "application/postscript", ".ps" },
    { "application/rtf", ".rtf" },
    { "application/x-bcpio", ".bcpio" },
    { "application/x-cpio", ".cpio" },
    { "application/x-csh", ".csh" },
    { "application/x-dvi", ".dvi" },
    { "application/x-gtar", ".gtar" },
    { "application/x-hdf", ".hdf" },
    { "application/x-latex", ".latex" },
    { "application/x-mif", ".mif" },
    { "application/x-netcdf", ".nc" },
    { "application/x-netcdf", ".cdf" },
    { "application/x-ns-proxy-autoconfig", ".pac" },
    { "application/x-patch", ".patch" },
    { "application/x-sh", ".sh" },
    { "application/x-shar", ".shar" },
    { "application/x-sv4cpio", ".sv4cpio" },
    { "application/x-sv4crc", ".sv4crc" },
    { "application/x-tar", ".tar" },
    { "application/x-tgz", ".tgz" },
    { "application/x-tcl", ".tcl" },
    { "application/x-tex", ".tex" },
    { "application/x-texinfo", ".texinfo" },
    { "application/x-texinfo", ".texi" },
    { "application/x-troff", ".t" },
    { "application/x-troff", ".tr" },
    { "application/x-troff", ".roff" },
    { "application/x-troff-man", ".man" },
    { "application/x-troff-me", ".me" },
    { "application/x-troff-ms", ".ms" },
    { "application/x-ustar", ".ustar" },
    { "application/x-wais-source", ".src" },
    { "application/zip", ".zip" },
    { "audio/basic", ".au snd" },
    { "audio/x-aiff", ".aif" },
    { "audio/x-aiff", ".aiff" },
    { "audio/x-aiff", ".aifc" },
    { "audio/x-wav", ".wav" },
    { "audio/x-wav", ".ram" },
    { "image/ief", ".ief" },
    { "image/jpeg", ".jpeg" },
    { "image/jpeg", ".jpe" },
    { "image/tiff", ".tiff" },
    { "image/tiff", ".tif" },
    { "image/x-cmu-raster", ".ras" },
    { "image/x-portable-anymap", ".pnm" },
    { "image/x-portable-bitmap", ".pbm" },
    { "image/x-portable-graymap", ".pgm" },
    { "image/x-portable-pixmap", ".ppm" },
    { "image/x-rgb", ".rgb" },
    { "image/x-xbitmap", ".xbm" },
    { "image/x-xpixmap", ".xpm" },
    { "image/x-xwindowdump", ".xwd" },
    { "text/html", ".cfm" },
    { "text/html", ".shtm" },
    { "text/html", ".shtml" },
    { "text/richtext", ".rtx" },
    { "text/tab-separated-values", ".tsv" },
    { "text/x-setext", ".etx" },
    { "video/mpeg", ".mpeg" },
    { "video/mpeg", ".mpg" },
    { "video/mpeg", ".mpe" },
    { "video/quicktime", ".qt" },
    { "video/quicktime", ".mov" },
    { "video/mp4", ".mp4" },
    { "video/x-msvideo", ".avi" },
    { "video/x-sgi-movie", ".movie" },
    { "application/json", ".cgi" },
    { "application/x-x509-ca-cert", ".crt"},
    { NULL, NULL},
};

/*
    Standard HTTP error codes
 */
static WebsError websErrors[] = {
    { 200, "OK" },
    { 201, "Created" },
    { 204, "No Content" },
    { 205, "Reset Content" },
    { 206, "Partial Content" },
    { 301, "Redirect" },
    { 302, "Redirect" },
    { 304, "Not Modified" },
    { 400, "Bad Request" },
    { 401, "Unauthorized" },
    { 402, "Payment required" },
    { 403, "Forbidden" },
    { 404, "Not Found" },
    { 405, "Access Denied" },
    { 406, "Not Acceptable" },
    { 408, "Request Timeout" },
    { 413, "Request too large" },
    { 500, "Internal Server Error" },
    { 501, "Not Implemented" },
    { 503, "Service Unavailable" },
    { 0, NULL }
};

/* Callback ID */

// pthread_mutex_t mutex_session = PTHREAD_MUTEX_INITIALIZER;
 pthread_rwlock_t rw_session = PTHREAD_RWLOCK_INITIALIZER;
/**************************** Forward Declarations ****************************/


//static int      getTimeSinceMark(Webs *wp);
static void     parseFirstLine(Webs *wp);
static void     parseHeaders(Webs *wp);

void     		pruneSessions();

PUBLIC void websHeader(webs_t wp)
{
//   websWrite(wp,"Status: 200\r\n");
//   websWrite(wp,"Content-Type: application/json\r\n");
 //  websWrite(wp,"\r\n");
   websResponse(wp, 200, 0);
}


/*********************************** Code *************************************/
int websOpen()
{
    WebsMime *mt = NULL;

    webs = NULL;
    websMax = 0;

    websActionOpen();
    if (websOpenRoute() < 0)
	{
        return -1;
    }
    if (websOpenAuth(0) < 0)
    {
        return -1;
    }
    // Mime映射表
    websMime = hashCreate(WEBS_HASH_INIT * 4);
    for (mt = websMimeList; mt->type; mt++)
	{
        hashEnter(websMime, mt->ext, valueString(mt->type, 0), 0);
    }

    return 0;
}


PUBLIC void websClose()
{
    websCloseRoute();
    //websCloseAuth();

    wfree(websHostUrl);
    websHostUrl = NULL;
    wfree(websIpAddrUrl);
    websIpAddrUrl = NULL;
    hashFree(websMime);

	return ;
}


/*
 * 函数名: initWebs
 *
 * 函数描述: 还原Webs的初始化状态
 * @wp
 * @flags  wp->flags
 * @reuse 1 保留wp->ipaddr wp->ifaddr和timeout 0-不保留 wp->timeout = -1;
 *
 * 返回值: 无
 */
void initWebs(Webs *wp, int flags, int reuse)
{
    char ipaddr[ME_MAX_IP];
    char ifaddr[ME_MAX_IP];
    int timeout;

    if (reuse)
	{
        timeout = wp->timeout;
        scopy(ipaddr, sizeof(ipaddr), wp->ipaddr);
        scopy(ifaddr, sizeof(ifaddr), wp->ifaddr);
    }
	else
	{

        timeout = -1;
    }

    memset(wp, 0, sizeof(Webs));

    wp->flags = flags;
    wp->state = WEBS_READY;
    wp->timeout = timeout;
    wp->docfd = -1;
    wp->txLen = -1;
    wp->rxLen = -1;
    wp->code = HTTP_CODE_OK;

    if (reuse)
	{
        scopy(wp->ipaddr, sizeof(wp->ipaddr), ipaddr);
        scopy(wp->ifaddr, sizeof(wp->ifaddr), ifaddr);
    }

    return ;
}


void termWebs(Webs *wp, int reuse)
{
    /*
        Some of this is done elsewhere, but keep this here for when a shutdown is done and there are open connections.
     */
     int i = 0;
    if ((wp->timeout >= 0) && (!reuse))
	{
      //  websCancelTimeout(wp);
    }
    if(wp->authDetails)
    {
        //LOGD("-----------------1\n");
        wfree(wp->authDetails);
    	wp->authDetails = NULL;
    }
    if(wp->authResponse)
    {//LOGD("-----------------2\n");
        wfree(wp->authResponse);
    	wp->authResponse = NULL;
    }

    if(wp->contentType)
    {//LOGD("-----------------4\n");
        wfree(wp->contentType);
    	wp->contentType = NULL;
    }
    if(wp->cookie)
    {//LOGD("-----------------5\n");
        wfree(wp->cookie);
    	wp->cookie = NULL;
    }
    if(wp->decodedQuery)
    {//LOGD("-----------------6\n");
        wfree(wp->decodedQuery);
        wp->decodedQuery = NULL;
    }
    if(wp->digest)
    {//LOGD("-----------------7\n");
        wfree(wp->digest);
        wp->digest=NULL;
    }

    if(wp->filename)
    {//LOGD("-----------------9\n");
        wfree(wp->filename);
        wp->filename=NULL;
    }
    if(wp->host)
    {//LOGD("-----------------10\n");
        wfree(wp->host);
        wp->host=NULL;
    }
    if(wp->method)
    {//LOGD("-----------------11\n");
        wfree(wp->method);
        wp->method=NULL;
    }
    if(wp->password)
    {//LOGD("-----------------12\n");
        wfree(wp->password);
        wp->password=NULL;
    }
    if(wp->path)
    {//LOGD("-----------------13\n");
        wfree(wp->path);
        wp->path=NULL;
    }
    if(wp->pathlast)
    {//LOGD("-----------------14\n");
        wfree(wp->pathlast);
        wp->pathlast=NULL;
    }
    if(wp->protoVersion)
    {//LOGD("-----------------15\n");
        wfree(wp->protoVersion);
        wp->protoVersion=NULL;
    }

    if(wp->putname)
    {//LOGD("-----------------17\n");
        wfree(wp->putname);
        wp->putname=NULL;
    }
    if(wp->query)
    {//LOGD("-----------------18\n");
        wfree(wp->query);
        wp->query=NULL;
    }
    if(wp->realm)
    {//LOGD("-----------------19\n");
        wfree(wp->realm);
        wp->realm=NULL;
    }
    if(wp->referrer)
    {//LOGD("-----------------20\n");
        wfree(wp->referrer);
        wp->referrer=NULL;
    }
    if(wp->responseCookie)
    {//LOGD("-----------------21\n");
        wfree(wp->responseCookie);
        wp->responseCookie=NULL;
    }
    if(wp->responseCookieHash)
    {//LOGD("-----------------22\n");
        wfree(wp->responseCookieHash);
        wp->responseCookieHash=NULL;
    }
    if(wp->responseX_Csrf_TokenHash)
    {//LOGD("-----------------23\n");
        wfree(wp->responseX_Csrf_TokenHash);
        wp->responseX_Csrf_TokenHash=NULL;
    }
    if(wp->url)
    {//LOGD("-----------------24\n");
        wfree(wp->url);
        wp->url=NULL;
    }
    if(wp->queryString)
    {
        //LOGD("-----------------25\n");

        wfree(wp->queryString);
        wp->queryString=NULL;
    }
    if(wp->userAgent)
    {//LOGD("-----------------26\n");
        wfree(wp->userAgent);
        wp->userAgent=NULL;
    }
    if(wp->username)
    {//LOGD("-----------------27\n");
        wfree(wp->username);
        wp->username=NULL;
    }
    if(wp->session_id)
    {//LOGD("-----------------28\n");
        wfree(wp->session_id);
        wp->session_id=NULL;
    }
    if(wp->session)
    {//LOGD("-----------------29\n");
        if(wp->session->id)
        {
            wfree(wp->session->id);
        }
        wfree(wp->session);

    }
    if(wp->cnonce)
    {//LOGD("-----------------29\n");
        wfree(wp->cnonce);
    	wp->cnonce = NULL;
    }
    if(wp->digestUri)
    {//LOGD("-----------------30\n");
        wfree(wp->digestUri);
    	wp->digestUri = NULL;
    }
    if(wp->opaque)
    {//LOGD("-----------------31\n");
        wfree(wp->opaque);
    	wp->opaque = NULL;
    }
    if(wp->nc)
    {//LOGD("-----------------32\n");
        wfree(wp->nc);
    	wp->nc = NULL;
    }
    if(wp->nonce)
    {//LOGD("-----------------33\n");
        wfree(wp->nonce);
    	wp->nonce = NULL;
    }
    if(wp->qop)
    {//LOGD("-----------------34\n");
        wfree(wp->qop);
    	wp->qop = NULL;
    }
    if(wp->wsse_created)
    {//LOGD("-----------------35\n");
        wfree(wp->wsse_created);
        wp->wsse_created = NULL;
    }
    if(wp->wsse_nonce)
    {//LOGD("-----------------36\n");
        wfree(wp->wsse_nonce);
        wp->wsse_nonce = NULL;
    }
    if(wp->wsse_passwordDigest)
    {//LOGD("-----------------37\n");
        wfree(wp->wsse_passwordDigest);
        wp->wsse_passwordDigest = NULL;
    }

	for(i = 0;i < 6;++i){
        if(wp->upload_filename[i])
        {
        	wfree(wp->upload_filename[i]);
    	}
    }
    if(wp->uploadType)
    {//LOGD("-----------------38\n");
        //wp->upload_filename = NULL;
        wfree(wp->uploadType);
        wp->uploadType = NULL;
    }
	return ;
}


PUBLIC int websAlloc(int sid)
{
    Webs    *wp;
    int     wid;

    if ((wid = wallocObject(&webs, &websMax, sizeof(Webs))) < 0) {
        return -1;
    }
    wp = webs[wid];
    initWebs(wp, 0, 0);
    wp->wid = wid;
    wp->sid = sid;
    wp->timestamp = time(0);
    return wid;
}





PUBLIC void websFree(Webs *wp)
{
    termWebs(wp, 0);
    websMax = wfreeHandle(&webs, wp->wid);
    wfree(wp);
}

/*
 * 函数名 web_process_request
 *
 *
 * 函数描述: 处理客户端的请求
 */
void web_process_requests(Webs *wp)
{
    char *fixMode_IE = NULL;

    parseFirstLine(wp);
    parseHeaders(wp);
    wp->state = WEBS_READY;

    fixMode_IE = FCGX_GetParam("HTTP_FIXIE_MODE", wp->req->envp);
    if(slen(fixMode_IE))
    {
        wp->fixIEMode = TRUE;
    }
    else
    {
        wp->fixIEMode = FALSE;
    }
    webs_route_request(wp);

    return ;
}
#if 0
//all the fastcgi request's processing start form here
bool parseIncoming(Webs *wp)
{
    //BOOL is_ssid_valid = FALSE;
    char *id = NULL;
    char *cookie_hash = NULL;
    char *x_csrf_token = NULL;
    char *fixie  = NULL;

    /*
        Parse the first line of the Http header
     */
    parseFirstLine(wp);
    parseHeaders(wp);
    /*(wp->rxChunkState || wp->rxLen > 0) ? WEBS_CONTENT :*/
    wp->state = WEBS_READY;

    fixie = FCGX_GetParam("HTTP_FIXIE_MODE", wp->req->envp);
    if(slen(fixie))
    {
        wp->fixIEMode = TRUE;
    }
    else
    {
        wp->fixIEMode = FALSE;
    }
    //try get our session in http header
    //we use custom http header pass the SSID,when we need one tab page one session on browser end.
    /*
    we check SSID and X-token is not modify here,before we get auth verify sucess! we deal with the session first!
    */
    id = sclone(FCGX_GetParam("HTTP_S_HASH", wp->req->envp));
    cookie_hash = sclone(FCGX_GetParam("HTTP_C_HASH", wp->req->envp));
    x_csrf_token = sclone(FCGX_GetParam("HTTP_X_HASH", wp->req->envp));
    //verify the cookie,whether the client has modify it!
#if 0
    if((id != NULL) && (cookie_hash != NULL) && slen(id) && slen(cookie_hash))
    {
        char dstBuf[256]={0};
        char* result = NULL;
        fmt(dstBuf, sizeof(dstBuf), "%s:%s", id, COOKIE_SALT_CODE);
        result = websMD5(dstBuf);
        is_ssid_valid = smatch(result, cookie_hash);
        LOGD("SSID is not modified:%d\n",is_ssid_valid);
        wfree(result);
    }
#endif

    wfree(cookie_hash);
    wfree(x_csrf_token);
    websRouteRequest(wp, id);
    wfree(id);

    return 1;
}
#endif

/*
    Parse the first line of a HTTP request
 */
static void parseFirstLine(Webs *wp)
{
    char  *protoVer,*value;
    char* secure_flag;

    wp->method = supper(sclone(FCGX_GetParam("REQUEST_METHOD", wp->req->envp)));
    value = FCGX_GetParam("SERVER_ADDR",wp->req->envp);
    if(value)
	{
        memset(wp->ifaddr,0,sizeof(wp->ifaddr));
        strcpy(wp->ifaddr,value);
    }

    value = FCGX_GetParam("REMOTE_ADDR",wp->req->envp);
    if(value)
	{
        memset(wp->ipaddr,0,sizeof(wp->ipaddr));
        strcpy(wp->ipaddr,value);
    }

    wp->url = sclone(FCGX_GetParam("REQUEST_URI",wp->req->envp));
    wp->path = sclone(FCGX_GetParam("SCRIPT_NAME",wp->req->envp));
    wp->queryString = sclone(FCGX_GetParam("QUERY_STRING",wp->req->envp));

    wp->pathlast = NULL;
    char *pathLast = strrchr(wp->path, '/');
    if (pathLast)
    {
        pathLast++;
        int size = wp->path + strlen(wp->path) - pathLast;
        if (size > 0 && (wp->pathlast = malloc(size+1)))
        {
            memcpy(wp->pathlast, pathLast, size);
            wp->pathlast[size] = '\0';
        }

    }

    if(strstr(wp->url, "Capture"))
	{
        wp->ext = ".jpeg";
    }
	else if(strstr(wp->url, "frmGetConfigFile") || strstr(wp->url, "frmSetConfigFile"))
	{
        wp->ext = ".gz";//or .bin
    }
    else if (strstr(wp->url, "upload"))
    {
        wp->ext = ".html";
    }
	else
	{
        wp->ext = ".cgi";
    }
    wp->filename = sclone(FCGX_GetParam("SCRIPT_FILENAME", wp->req->envp));
    wp->host = sclone(FCGX_GetParam("HTTP_HOST", wp->req->envp));
    protoVer = FCGX_GetParam("SERVER_PROTOCOL", wp->req->envp);
    secure_flag = FCGX_GetParam("HTTPS", wp->req->envp);
    if(smatch(secure_flag,"on"))
	{
       wp->protocol =  "https" ;
    }
	else
	{
        wp->protocol = "http";
    }
    wp->protoVersion = sclone(protoVer);
    wp->port = strtol(FCGX_GetParam("SERVER_PORT",wp->req->envp),NULL,10);

    //parse authtype by path
    //goform req parsed auth_type is NULL,jump auth Steps
    {
        BOOL is_digest_authtype,is_basic_authtype;

        wp->authType = NULL;//default

        is_digest_authtype  = strncmp(wp->path,"/digest",slen("/digest")) == 0;
        is_basic_authtype  = strncmp(wp->path,"/basic",slen("/basic")) == 0;

        if(is_digest_authtype){
            wp->authType = "digest";
        }

        if(is_basic_authtype){
            wp->authType = "basic";
        }
    }
}


/*
    Parse a full request
    HTTP_USER_AGENT
    HTTP_AUTHORIZATION
    CONTENT_TYPE
    CONTENT_LENGTH
    HTTP_COOKIE
 */
static void parseHeaders(Webs *wp)
{
    char *value = NULL;
    int len = 0;
    char *postbuf = NULL;
    char *pStart = NULL;

    /*
        Parse the header and create the Http header keyword variables
        We rewrite the header as we go for non-local requests.  NOTE: this
        modifies the header string directly and tokenizes each line with '\0'.
    */

       /*
            Track the requesting agent (browser) type
         */
    wp->session_id = sclone(FCGX_GetParam("HTTP_CV_SESSION_ID",wp->req->envp));
//	LOGD("session_id:%s\n",wp->session_id);
	wp->userAgent = sclone(FCGX_GetParam("HTTP_USER_AGENT",wp->req->envp));

	value = FCGX_GetParam("HTTP_AUTHORIZATION", wp->req->envp);
	if (value)
	{
		pStart = strchr(value,' ');
		if (pStart)
		{
			*pStart = '\0';
			/*if(scaselessmatch(value, "X-Digest")){
				wp->authType = "digest";
			}else if(scaselessmatch(value, "X-Basic")){
				wp->authType = "basic";
			}else{
				wp->authType = "";
			}*/
			pStart++;

			wp->authDetails = sclone(pStart);
		}
		else
		{
            wp->authDetails = NULL;
		}

	}

    value = FCGX_GetParam("CONTENT_TYPE", wp->req->envp);
	if(value)
	{
		wp->contentType = sclone(value);
	}


    value = FCGX_GetParam("CONTENT_LENGTH", wp->req->envp);//post data length
    if (value)
        len = strtol(value, NULL, 10);
    /*
	    Bug Fixed!
	    when file upload !we don't need to malloc spaces for incoming data.because nginx never send it!
    	*/
    if(len > 0)
	{//read post
	    if (strcmp(wp->pathlast, "upload") != 0)
	    {
            postbuf = malloc(sizeof(char)*len+1);
            memset(postbuf, 0, sizeof(char)*len + 1);
            if(postbuf)
            {

             FCGX_GetStr(postbuf, len, wp->req->in);
             wp->query = postbuf;
            }
        }
        else
        {
            upload_file_save_as(len, wp);
        }
    }


    value = FCGX_GetParam("HTTP_COOKIE", wp->req->envp);
	if (value)
	{
		wp->cookie = sclone(value);
	}
	else
	{
		wp->cookie = NULL;
	}

}

/*
    Output a HTTP response back to the browser. If redirect is set to a URL, the browser will be sent to this location.
 */
PUBLIC void websResponse(Webs *wp, int code, char *message)
{
    WebsKey* key;
    //ssize   len;

    websSetStatus(wp, code);
    if (wp->authResponse)
	{
        websWriteHeader(wp, "WWW-Authenticate", "%s", wp->authResponse);
    }
    if (wp->authResponse)
	{
        websWriteHeader(wp, "S-HASH", "330b975b7b2817e0ef479540a2bdb290");
        websWriteHeader(wp, "C-HASH", "fddfbcb795cd02aa3d7096820a0a31ce");
        websWriteHeader(wp, "X-HASH", "d4f9baf042d2a5892c98e4f258d7f6ea");
    }

    if (code == 302 && message)
	{
        websWriteHeader(wp, "Location", "%s", message);
    }

    if ((key = hashLookup(websMime, wp->ext)) != 0)
	{
        websWriteHeader(wp, "Content-Type", "%s",key->content.value.string);
    }


    /*if (wp->responseCookie)
	{
#ifdef SESSION_BASEON_COOKIE
            websWriteHeader(wp, "Set-Cookie", "%s", wp->responseCookie);
    		if(wp->responseCookieHash)
				websWriteHeader(wp, "Set-Cookie", "%s", wp->responseCookieHash);
    		if(wp->responseX_Csrf_TokenHash)
				websWriteHeader(wp, "Set-Cookie", "%s", wp->responseX_Csrf_TokenHash);
            websWriteHeader(wp, "Cache-Control", "%s", "no-cache=\"set-cookie\"");
#else
            websWriteHeader(wp, "S-HASH", "%s", wp->responseCookie);
            websWriteHeader(wp, "C-HASH", "%s", wp->responseCookieHash);
            websWriteHeader(wp, "X-HASH", "%s", wp->responseX_Csrf_TokenHash);
#endif
    }*/
    //cach 策略 防止浏览器缓存fcgi返回的结果
    websWriteHeader(wp, "Cache-Control", "%s", "no-cache");
    websWriteHeader(wp, "Pragma", "%s", "no-cache");
    websWriteHeader(wp, "Expires", "%d", -1);

    websWriteHeader(wp, "Access-Control-Allow-Origin", "*");
    websWriteHeader(wp, "Access-Control-Allow-Headers", "User-Agent,Authorization,Www-Authenticate,Content-Type,Content-Length,Host,Origin,Referer");
    websWriteHeader(wp, "Access-Control-Allow-Methods", "*");

    websWriteEndHeaders(wp);

   /*  if (!smatch(wp->method, "HEAD") && message && *message && code == 200)
	 {
        len = slen(message);
        websWriteBlock(wp, message, len);
     }
    if (!smatch(wp->method, "HEAD") && message && *message) {
        len = slen(message);
        websWriteHeaders(wp, len + 2, 0);
        websWriteEndHeaders(wp);
        websWriteBlock(wp, message, len);
        websWriteBlock(wp, "\r\n", 2);
    } else {
        websWriteHeaders(wp, 0, 0);
        websWriteEndHeaders(wp);
    }
    websDone(wp);*/
}


#if 0
static char *makeUri(char *scheme, char *host, int port, char *path)
{
    return sfmt("%s://%s:%d%s", scheme, host, port, path);
}
#endif


/*
    Redirect the user to another webs page
 */
PUBLIC void websRedirect(Webs *wp, char *uri)
{
   /* char    *message, *location, *scheme, *host, *pstr;
    char    hostbuf[ME_GOAHEAD_LIMIT_STRING];
    bool    secure, fullyQualified;
    ssize   len;
    int     originalPort, port;

    message = location = NULL;



    message = sfmt("<html><head></head><body>\r\n\
        This document has moved to a new <a href=\"%s\">location</a>.\r\n\
        Please update your documents to reflect the new location.\r\n\
        </body></html>\r\n", uri);
    len = slen(message);
    websSetStatus(wp, HTTP_CODE_MOVED_TEMPORARILY);
    websWriteHeaders(wp, len + 2, uri);
    websWriteEndHeaders(wp);
    websWriteBlock(wp, message, len);
    websWriteBlock(wp, "\r\n", 2);
    websDone(wp);
    wfree(message);
    wfree(location);*/
}


PUBLIC int websRedirectByStatus(Webs *wp, int status)
{
    WebsKey     *key;
    char        code[16], *uri;

    if (wp->route && wp->route->redirects >= 0) {
        itosbuf(code, sizeof(code), status, 10);
        if ((key = hashLookup(wp->route->redirects, code)) != 0) {
            uri = key->content.value.string;
        } else {
            return -1;
        }
        websRedirect(wp, uri);
    } else {
        if (status == HTTP_CODE_UNAUTHORIZED) {
            websError(wp, status, "Access Denied. User not logged in.");
        } else {
            websError(wp, status, 0);
        }
    }
    return 0;
}


/*
    Escape HTML to escape defined characters (prevent cross-site scripting)
    Returns an allocated string.
 */
PUBLIC char *websEscapeHtml(char *html)
{
    char    *ip, *result, *op;
    int     len;

    if (!html) {
        return sclone("");
    }
    for (len = 1, ip = html; *ip; ip++, len++) {
        if (charMatch[(int) (uchar) *ip] & WEBS_ENCODE_HTML) {
            len += 5;
        }
    }
    if ((result = walloc(len)) == 0) {
        return 0;
    }
    /*
        Leave room for the biggest expansion
     */
    op = result;
    while (*html != '\0') {
        if (charMatch[(uchar) *html] & WEBS_ENCODE_HTML) {
            if (*html == '&') {
                strcpy(op, "&amp;");
                op += 5;
            } else if (*html == '<') {
                strcpy(op, "&lt;");
                op += 4;
            } else if (*html == '>') {
                strcpy(op, "&gt;");
                op += 4;
            } else if (*html == '#') {
                strcpy(op, "&#35;");
                op += 5;
            } else if (*html == '(') {
                strcpy(op, "&#40;");
                op += 5;
            } else if (*html == ')') {
                strcpy(op, "&#41;");
                op += 5;
            } else if (*html == '"') {
                strcpy(op, "&quot;");
                op += 6;
            } else if (*html == '\'') {
                strcpy(op, "&#39;");
                op += 5;
            } else {
            }
            html++;
        } else {
            *op++ = *html++;
        }
    }
    *op = '\0';
    return result;
}


PUBLIC int websWriteHeader(Webs *wp, char *key, char *fmt, ...)
{
    va_list     vargs;
    char        *buf;

    if (!(wp->flags & WEBS_RESPONSE_TRACED)) {
        wp->flags |= WEBS_RESPONSE_TRACED;

    }
    if (key) {
        if (websWriteBlock(wp, key, strlen(key)) < 0) {
            return -1;
        }
        if (websWriteBlock(wp, ": ", 2) < 0) {
            return -1;
        }

    }
    if (fmt) {
        va_start(vargs, fmt);
        if ((buf = sfmtv(fmt, vargs)) == 0) {
            DEBUGV3("\nwebsWrite lost data, buffer overflow\n");
            return -1;
        }
        va_end(vargs);
        if (websWriteBlock(wp, buf, strlen(buf)) < 0) {
            return -1;
        }
        wfree(buf);
        if (websWriteBlock(wp, "\r\n", 2) != 2) {
            return -1;
        }
    }
    return 0;
}


PUBLIC void websSetStatus(Webs *wp, int code)
{
	char buf[64]={0};
    wp->code = (code & WEBS_CODE_MASK);
    if (code & WEBS_CLOSE) {
        wp->flags &= ~WEBS_KEEP_ALIVE;
    }

    sprintf(buf,"Status: %d\r\n",code);
    websWrite(wp,buf);
}


/*
    Write a set of headers. Does not write the trailing blank line so callers can add more headers.
    Set length to -1 if unknown and transfer-chunk-encoding will be employed.
 */
PUBLIC void websWriteHeaders(Webs *wp, ssize length, char *location)
{
    WebsKey     *key;

    if (wp->authResponse) {
        websWriteHeader(wp, "WWW-Authenticate", "%s", wp->authResponse);
    }

    if (location) {
        websWriteHeader(wp, "Location", "%s", location);
    } else if ((key = hashLookup(websMime, wp->ext)) != 0) {
        websWriteHeader(wp, "Content-Type", "%s", key->content.value.string);
    }
    if (wp->responseCookie && wp->responseCookieHash) {
        websWriteHeader(wp, "Set-Cookie", "%s", wp->responseCookie);
		websWriteHeader(wp, "Set-Cookie", "%s", wp->responseCookieHash);
        websWriteHeader(wp, "Cache-Control", "%s", "no-cache=\"set-cookie\"");
    }

    //websWriteHeader(wp, "Connection", "%s", "keep-alive");
    //websWriteHeader(wp, "Keep-Alive", "%s", "timeout=60, max=74");


#ifdef ME_GOAHEAD_XFRAME_HEADER
   //     if (*ME_GOAHEAD_XFRAME_HEADER) {
    //        websWriteHeader(wp, "X-Frame-Options", "%s", ME_GOAHEAD_XFRAME_HEADER);
     //   }
#endif

}


PUBLIC void websWriteEndHeaders(Webs *wp)
{
    /*
        By omitting the "\r\n" delimiter after the headers, chunks can emit "\r\nSize\r\n" as a single chunk delimiter
     */
    //if (wp->txLen >= 0) {
        websWriteBlock(wp, "\r\n", 2);
   // }
    wp->flags |= WEBS_HEADERS_CREATED;
  //  if (wp->txLen < 0) {
  //      wp->flags |= WEBS_CHUNKING;
  //  }
}


PUBLIC void websSetTxLength(Webs *wp, ssize length)
{
    wp->txLen = length;
}


/*
    Do formatted output to the browser. This is the public Javascript and form write procedure.
 */
PUBLIC ssize websWrite(Webs *wp, char *fmt, ...)
{
    va_list     vargs;
    char        *buf;
    ssize       rc;

    va_start(vargs, fmt);

    buf = NULL;
    rc = 0;
    if ((buf = sfmtv(fmt, vargs)) == 0) {
        DEBUGV3("websWrite lost data, buffer overflow");
    }
    va_end(vargs);
    if (buf) {
        rc = websWriteBlock(wp, buf, strlen(buf));
        wfree(buf);
    }
    return rc;
}


/*
    Write a block of data of length to the user's browser. Output is buffered and flushed via websFlush.
    This routine will never return "short". i.e. it will return the requested size to write or -1.
    Buffer data. Will flush as required. May return -1 on write errors.
 */
PUBLIC ssize websWriteBlock(Webs *wp, char *buf, ssize size)
{
    return FCGX_PutStr(buf,size,wp->req->out);
}


/*
    Decode a URL (or part thereof). Allows insitu decoding.
 */
PUBLIC void websDecodeUrl(char *decoded, char *input, ssize len)
{
    char    *ip,  *op;
    int     num, i, c;

    if (len < 0) {
        len = strlen(input);
    }
    op = decoded;
    for (ip = input; *ip && len > 0; ip++, op++) {
        if (*ip == '+') {
            *op = ' ';
        } else if (*ip == '%' && isxdigit((uchar) ip[1]) && isxdigit((uchar) ip[2])) {
            /*
                Convert %nn to a single character
             */
            ip++;
            for (i = 0, num = 0; i < 2; i++, ip++) {
                c = tolower((uchar) *ip);
                if (c >= 'a' && c <= 'f') {
                    num = (num * 16) + 10 + c - 'a';
                } else {
                    num = (num * 16) + c - '0';
                }
            }
            *op = (char) num;
            ip--;

        } else {
            *op = *ip;
        }
        len--;
    }
    *op = '\0';
}









PUBLIC int websRewriteRequest(Webs *wp, char *url)
{
    char    *buf, *path;

    wfree(wp->url);
    wp->url = sclone(url);
    wfree(wp->path);
    wp->path = 0;

    if (websUrlParse(url, &buf, NULL, NULL, NULL, &path, NULL, NULL, NULL) < 0) {
        return -1;
    }
    wp->path = sclone(path);
    wfree(wp->filename);
    wp->filename = 0;
    wp->flags |= WEBS_REROUTE;
    wfree(buf);
    return 0;
}

//检测wp变量是否在wes链表中
PUBLIC bool websValid(Webs *wp)
{
    int     wid;

    for (wid = 0; wid < websMax; wid++)
	{
        if (wp == webs[wid])
		{
            return 1;
        }
    }
    return 0;
}


/*
    Build an ASCII time string.  If sbuf is NULL we use the current time, else we use the last modified time of sbuf;
 */
PUBLIC char *websGetDateString(time_t t)
{
    WebsTime    now;
    struct tm   tm;
    char        *cp;

    if (t <= 0) {
        time(&now);
    } else {
        now = t;
    }
#if ME_UNIX_LIKE
    gmtime_r(&now, &tm);
#else
    {
        struct tm *tp;
        tp = gmtime(&now);
        tm = *tp;
    }
#endif
    if ((cp = asctime(&tm)) != NULL) {
        cp[strlen(cp) - 1] = '\0';
        return sclone(cp);
    }
    return NULL;
}


/*
    Take not of the request activity and mark the time. Set a timestamp so that, later, we can return the number of seconds
    since we made the mark.
 */
PUBLIC void websNoteRequestActivity(Webs *wp)
{
    wp->timestamp = time(0);
}


/*
    Get the number of seconds since the last mark.
 */
#if 0
static int getTimeSinceMark(Webs *wp)
{
    return (int) (time(0) - wp->timestamp);
}
#endif


PUBLIC bool websValidUriChars(char *uri)
{
    ssize   pos;

    if (uri == 0 || *uri == 0) {
        return 1;
    }
    pos = strspn(uri, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=%");
    if (pos < slen(uri)) {
        DEBUGV3("Bad character in URI at \"%s\"", &uri[pos]);
        return 0;
    }
    return 1;
}


/*
    Parse the URL. A single buffer is allocated to store the parsed URL in *pbuf. This must be freed by the caller.
 */
PUBLIC int websUrlParse(char *url, char **pbuf, char **pscheme, char **phost, char **pport, char **ppath, char **pext,
        char **preference, char **pquery)
{
    char    *tok, *delim, *host, *path, *port, *scheme, *reference, *query, *ext, *buf, *buf2;
    ssize   buflen, ulen, len;
    int     sep;

    if (url == 0) {
        url = "";
    }
    /*
        Allocate twice. Need to null terminate the host so have to copy the path.
     */
    ulen = strlen(url);
    len = ulen + 1;
    buflen = len * 2;
    if ((buf = walloc(buflen)) == NULL) {
        return -1;
    }
    buf2 = &buf[ulen + 1];
    sncopy(buf, len, url, ulen);
    sncopy(buf2, len, url, ulen);
    url = buf;

    scheme = 0;
    host = 0;
    port = 0;
    path = 0;
    ext = 0;
    query = 0;
    reference = 0;
    tok = buf;
    sep = '/';

    /*
        [scheme://][hostname[:port]][/path[.ext]][#ref][?query]
        First trim query and then reference from the end
     */
    if ((query = strchr(tok, '?')) != NULL) {
        *query++ = '\0';
    }
    if ((reference = strchr(tok, '#')) != NULL) {
        *reference++ = '\0';
    }

    /*
        [scheme://][hostname[:port]][/path]
     */
    if ((delim = strstr(tok, "://")) != 0) {
        scheme = tok;
        *delim = '\0';
        tok = &delim[3];
    }

    /*
        [hostname[:port]][/path]
     */
    if (*tok == '[' && ((delim = strchr(tok, ']')) != 0)) {
        /* IPv6 [::] */
        host = &tok[1];
        *delim++ = '\0';
        tok = delim;

    } else if (*tok && *tok != '/' && *tok != ':' && (scheme || strchr(tok, ':'))) {
        /*
           Supported forms:
               scheme://hostname
               hostname[:port][/path]
         */
        host = tok;
        if ((tok = strpbrk(tok, ":/")) == 0) {
            tok = "";
        }
        /* Don't terminate the hostname yet, need to see if tok is a ':' for a port. */
    }

    /* [:port][/path] */
    if (*tok == ':') {
        /* Terminate hostname */
        *tok++ = '\0';
        port = tok;
        if ((tok = strchr(tok, '/')) == 0) {
            tok = "";
        }
    }

    /* [/path] */
    if (*tok) {
        /*
           Terminate hostname. This zeros the leading path slash.
           This will be repaired before returning if ppath is set
         */
        sep = *tok;
        *tok++ = '\0';
        path = tok;
        /* path[.ext[/extra]] */
        if ((tok = strrchr(path, '.')) != 0) {
            if (tok[1]) {
                if ((delim = strrchr(path, '/')) != 0) {
                    if (delim < tok) {
                        ext = tok;
                    }
                } else {
                    ext = tok;
                }
            }
        }
    }
    /*
        Pass back the requested fields
     */
    *pbuf = buf;
    if (pscheme) {
        if (scheme == 0) {
            scheme = "http";
        }
        *pscheme = scheme;
    }
    if (phost) {
        if (host == 0) {
            host = "localhost";
        }
        *phost = host;
    }
    if (pport) {
        *pport = port;
    }
    if (ppath) {
        if (path == 0) {
            scopy(buf2, 1, "/");
            path = buf2;
        } else {
            /* Copy path to reinsert leading slash */
            scopy(&buf2[1], len - 1, path);
            path = buf2;
            *path = sep;
        }
        *ppath = path;
    }
    if (pquery) {
        *pquery = query;
    }
    if (preference) {
        *preference = reference;
    }
    if (pext) {
#if ME_WIN_LIKE
        slower(ext);
#endif
        *pext = ext;
    }
    return 0;
}


/*
    Normalize a URI path to remove "./",  "../" and redundant separators.
    Note: this does not make an abs path and does not map separators nor change case.
    This validates the URI and expects it to begin with "/".
    Returns an allocated path, caller must free.
 */
PUBLIC char *websNormalizeUriPath(char *pathArg)
{
    char    *dupPath, *path, *sp, *dp, *mark, **segments;
    int     firstc, j, i, nseg, len;

    if (pathArg == 0 || *pathArg == '\0') {
        return sclone("");
    }
    len = (int) slen(pathArg);
    if ((dupPath = walloc(len + 2)) == 0) {
        return NULL;
    }
    strcpy(dupPath, pathArg);

    if ((segments = walloc(sizeof(char*) * (len + 1))) == 0) {
        wfree(dupPath);
        return NULL;
    }
    nseg = len = 0;
    firstc = *dupPath;
    for (mark = sp = dupPath; *sp; sp++) {
        if (*sp == '/') {
            *sp = '\0';
            while (sp[1] == '/') {
                sp++;
            }
            segments[nseg++] = mark;
            len += (int) (sp - mark);
            mark = sp + 1;
        }
    }
    segments[nseg++] = mark;
    len += (int) (sp - mark);
    for (j = i = 0; i < nseg; i++, j++) {
        sp = segments[i];
        if (sp[0] == '.') {
            if (sp[1] == '\0')  {
                if ((i+1) == nseg) {
                    /* Trim trailing "." */
                    segments[j] = "";
                } else {
                    j--;
                }
            } else if (sp[1] == '.' && sp[2] == '\0')  {
                j = max(j - 2, -1);
                if ((i+1) == nseg) {
                    nseg--;
                }
            } else {
                /* .more-chars */
                segments[j] = segments[i];
            }
        } else {
            segments[j] = segments[i];
        }
    }
    nseg = j;
    if ((path = walloc(len + nseg + 1)) != 0) {
        for (i = 0, dp = path; i < nseg; ) {
            strcpy(dp, segments[i]);
            len = (int) slen(segments[i]);
            dp += len;
            if (++i < nseg || (nseg == 1 && *segments[0] == '\0' && firstc == '/')) {
                *dp++ = '/';
            }
        }
        *dp = '\0';
    }
    wfree(dupPath);
    wfree(segments);
    return path;
}


/*
    Validate a URI path for use in a HTTP request line
    The URI must contain only valid characters and must being with "/" both before and after decoding.
    A decoded, normalized URI path is returned.
    The uri is modified. Returns an allocated path. Caller must free.
 */
PUBLIC char *websValidateUriPath(char *uri)
{
    if (uri == 0 || *uri != '/') {
        return 0;
    }
    if (!websValidUriChars(uri)) {
        return 0;
    }
    websDecodeUrl(uri, uri, -1);
    if ((uri = websNormalizeUriPath(uri)) == 0) {
        return 0;
    }
    if (*uri != '/' || strchr(uri, '\\')) {
        wfree(uri);
        return 0;
    }
    return uri;
}




PUBLIC void websSetCookie(Webs *wp, char *name, char *value, char *path, char *cookieDomain, int lifespan, int flags)
{
    WebsTime    when;
    char        *cp, *expiresAtt, *expires, *domainAtt, *domain, *secure, *httponly, *cookie, *old;

    if (path == 0) {
        path = "/";
    }
    if (!cookieDomain) {
        domain = sclone(wp->host);
        if ((cp = strchr(domain, ':')) != 0) {
            /* Strip port */
            *cp = '\0';
        }
        if (*domain && domain[strlen(domain) - 1] == '.') {
            /* Cleanup bonjour addresses with trailing dot */
            domain[strlen(domain) - 1] = '\0';
        }
    } else {
        domain = sclone(cookieDomain);
    }
    domainAtt = "";
    if (smatch(domain, "localhost")) {
        wfree(domain);
        domain = sclone("");
    } else {
        domainAtt = "; domain=";
        if (!strchr(domain, '.')) {
            old = domain;
            domain = sfmt(".%s", domain);
            wfree(old);
        }
    }
    if (lifespan > 0) {
        expiresAtt = "; expires=";
        when = time(0) + lifespan;
        if ((expires = ctime(&when)) != NULL) {
            expires[strlen(expires) - 1] = '\0';
        }

    } else {
        expiresAtt = "";
        expires = "";
    }
    /*
       Allow multiple cookie headers. Even if the same name. Later definitions take precedence
     */
    secure = "; secure";
    httponly = "; httponly";
    //we MD5 the true ssid for cookie check
    {
        char dstBuf[256]={0};
        char* result = NULL;
        fmt(dstBuf, sizeof(dstBuf), "%s:%s", value,COOKIE_SALT_CODE);

        result = websMD5(dstBuf);
        //set ssid
        cookie = sfmt("%s=%s; path=%s%s%s%s%s%s%s", name, value, path, domainAtt, domain, expiresAtt, expires, secure, httponly);
        if (wp->responseCookie) {
            old = wp->responseCookie;
            wp->responseCookie = sfmt("%s %s", wp->responseCookie, cookie);
            wfree(old);
            wfree(cookie);
        } else {
            wp->responseCookie = cookie;
        }
        //set cookie hash
        cookie = sfmt("%s=%s; path=%s%s%s%s%s%s%s", "C_HASH", result, path, domainAtt, domain, expiresAtt, expires, secure, httponly);
        if (wp->responseCookieHash) {
            old = wp->responseCookieHash;
            wp->responseCookieHash = sfmt("%s %s", wp->responseCookieHash, cookie);
            wfree(old);
            wfree(cookie);
        } else {
            wp->responseCookieHash = cookie;
        }
		//restore it in session var
		//websSetSessionVar(wp,"C_HASH",valueString(wp->responseCookieHash,VALUE_ALLOCATE));
		wfree(result);

		//set  responseX_Csrf_TokenHash
		fmt(dstBuf, sizeof(dstBuf), "%s:%s:%s", wp->responseCookie,wp->responseCookieHash,COOKIE_SALT_CODE);
		result = websMD5(dstBuf);

		//client need read this hash vals from cookie!so no need for httponly!
		httponly =  "";
		cookie = sfmt("%s=%s; path=%s%s%s%s%s%s%s", "X_HASH", result, path, domainAtt, domain, expiresAtt, expires, secure, httponly);
		if (wp->responseX_Csrf_TokenHash) {
			old = wp->responseX_Csrf_TokenHash;
			wp->responseX_Csrf_TokenHash = sfmt("%s %s", wp->responseX_Csrf_TokenHash, cookie);
			wfree(old);
			wfree(cookie);
		} else {
			wp->responseX_Csrf_TokenHash = cookie;
		}
		websSetSessionVar(wp,"X_HASH",valueString(result,VALUE_ALLOCATE));
		wfree(result);
    }

    DEBUGV3("\nwebsSetCookie=====================new Connection Request Done Login!=========[%s]====\n",cookie);
    wfree(domain);
}









 char *makeSessionID(Webs *wp)
{
    char        idBuf[64];
    static int  nextSession = 0;

    fmt(idBuf, sizeof(idBuf), "%08x%08x%d", PTOI(wp) + PTOI(wp->url), (int) time(0), nextSession++);
    return websMD5Block(idBuf, slen(idBuf), "");
}


WebsSession *websAllocSession(Webs *wp, char *id, int lifespan)
{
    WebsSession     *sp;

    if ((sp = walloc(sizeof(WebsSession))) == 0) {
        return 0;
    }
    sp->lifespan = lifespan;
    sp->expires = time(0) + lifespan;
    if (id == 0) {
        sp->id = makeSessionID(wp);
    } else {
        sp->id = sclone(id);
    }
    if ((sp->cache = hashCreate(WEBS_SESSION_HASH)) == 0) {
        wfree(sp->id);
        wfree(sp);
        return 0;
    }
    return sp;
}


 void freeSession(WebsSession *sp)
{
	DEBUGV3("[freeSession:%s]\n",sp->id);
    if (sp->cache >= 0) {
        hashFree(sp->cache);
        sp->cache = -1;
    }
    wfree(sp->id);
    wfree(sp);
}


PUBLIC char *websGetValueFromCookie(Webs *wp, char* name)
{
    char    *cookie, *cp, *value;
    ssize   len;
    int     quoted;

    cookie = wp->cookie;
    if (cookie && (value = strstr(cookie, name)) != 0) {
        value += strlen(name);
        while (isspace((uchar) *value) || *value == '=') {
            value++;
        }
        quoted = 0;
        if (*value == '"') {
            value++;
            quoted++;
        }
        for (cp = value; *cp; cp++) {
            if (quoted) {
                if (*cp == '"' && cp[-1] != '\\') {
                    break;
                }
            } else {
                if ((*cp == ',' || *cp == ';') && cp[-1] != '\\') {
                    break;
                }
            }
        }
        len = cp - value;
        if ((cp = walloc(len + 1)) == 0) {
            return 0;
        }
        strncpy(cp, value, len);
        cp[len] = '\0';
        return cp;
    }
    return NULL;
}




 WebsSession* websGetSessionBySSID(Webs *wp, char *key)
{
    WebsKey         *sym;

    if ((sym = hashLookup(sessions, key)) == 0) {

        return NULL;
    }

    return (WebsSession*) sym->content.value.symbol;

}

PUBLIC int websSetNewSession(Webs *wp)
{

    WebsKey         *sym;
    char * id;

    id = makeSessionID(wp);

    if (sessionCount > ME_GOAHEAD_LIMIT_SESSION_COUNT)
	{
        DEBUGV3("Too many sessions %d/%d", sessionCount, ME_GOAHEAD_LIMIT_SESSION_COUNT);
        wfree(id);
        return -1;
    }
    sessionCount++;

    if ((wp->session = websAllocSession(wp,id , ME_GOAHEAD_LIMIT_SESSION_LIFE)) == 0)
	{
        wfree(id);
        return 0;
    }
    if ((sym = hashEnter(sessions, wp->session->id, valueSymbol(wp->session), 0)) == 0)
	{
        wfree(id);
        freeSession(wp->session);
        return 0;
    }
    wp->session = (WebsSession*)sym->content.value.symbol;

#ifdef SESSION_BASEON_COOKIE
    websSetCookie(wp, WEBS_SESSION, wp->session->id, "/", NULL, /*ME_GOAHEAD_LIMIT_SESSION_LIFE*/0, 0);
#else
    {
        char dstBuf[256]={0};
        char* result = NULL;
        fmt(dstBuf, sizeof(dstBuf), "%s:%s", wp->session->id,COOKIE_SALT_CODE);
        result = websMD5(dstBuf);
        wp->responseCookie = sclone(wp->session->id);
        //set cookie hash
        wp->responseCookieHash = sclone(result);
		wfree(result);
		//set  responseX_Csrf_TokenHash
		fmt(dstBuf, sizeof(dstBuf), "%s:%s:%s", wp->responseCookie,wp->responseCookieHash,COOKIE_SALT_CODE);
		result = websMD5(dstBuf);
		wp->responseX_Csrf_TokenHash = sclone(result);
		websSetSessionVar(wp,"X_HASH",valueString(result,VALUE_ALLOCATE));
		wfree(result);
    }
#endif

    return 1;
}

PUBLIC void websRemoveSession(Webs *wp, char *key)
{
    hashDelete(sessions, key);
	 sessionCount--;

}



PUBLIC WebsValue *websGetSessionVar(Webs *wp, char *key)
{
    WebsSession     *sp;
    WebsKey         *sym;

    if ((sp = wp->session) != 0)
	{

        if ((sym = hashLookup(sp->cache, key)) == 0)
		{

            return NULL;
        }

        return (WebsValue*) (&sym->content);
    }

    return 0;
}


PUBLIC void websRemoveSessionVar(Webs *wp, char *key)
{
    WebsSession     *sp;

    if ((sp = wp->session) != 0) {

        hashDelete(sp->cache, key);

    }

}


PUBLIC int websSetSessionVar(Webs *wp, char *key, WebsValue value)
{
    WebsSession  *sp;

    if ((sp = wp->session) == 0)
	{
        return 0;
    }

    if (hashEnter(sp->cache, key, value, 0) == 0)
	{

        return -1;
    }

    return 0;
}

WebsHash GetSessionTbl()
{
    return sessions;
}

/*
    Output an error message and cleanup
 */
PUBLIC void websError(Webs *wp, int code, char *fmt, ...)
{
    va_list     args;
    char        *msg, *buf;
    char        *encoded;
    int         status;

    wp->error++;
    if (code & WEBS_CLOSE)
	{
        wp->flags &= ~WEBS_KEEP_ALIVE;
        wp->connError++;
    }
    status = code & WEBS_CODE_MASK;

    if (wp->rxRemaining && status != 200 && status != 301 && status != 302 && status != 401)
	{
        /* Close connection so we don't have to consume remaining content */
        wp->flags &= ~WEBS_KEEP_ALIVE;
    }
    encoded = websEscapeHtml(wp->url);
    wfree(wp->url);
    wp->url = encoded;
    if (fmt)
	{
        if (!(code & WEBS_NOLOG)) {
            va_start(args, fmt);
            msg = sfmtv(fmt, args);
            va_end(args);
            wfree(msg);
        }
        buf = sfmt("\
					<html>\r\n\
					    <head><title>Document Error: %s</title></head>\r\n\
					    <body>\r\n\
					        <h2>Access Error: %s</h2>\r\n\
					    </body>\r\n\
					</html>\r\n", websErrorMsg(code), websErrorMsg(code));
    }
	else
    {
        buf = 0;
    }

	if(wp->fixIEMode &&(code == 401 || code == 403))
	{
		char* out;
		Common_cJSON_T* jn = Common_cJSON_CreateObject();
		Common_cJSON_AddItemToObject(jn,"Status",Common_cJSON_CreateNumber(code));
		if(code == 401){
			Common_cJSON_AddItemToObject(jn,"Content",Common_cJSON_CreateString(wp->authResponse));
		}else if(code == 403){
			Common_cJSON_AddItemToObject(jn,"Content",Common_cJSON_CreateString(buf));
		}

		out = Common_cJSON_PrintUnformatted(jn, NULL);
		Common_cJSON_Delete(jn);
		websResponse(wp,200,out);//must return 200
		free(out);
	}
	else
	{
		websResponse(wp, code, buf);
	}

    wfree(buf);
}


/*
    Return the error message for a given code
 */
PUBLIC char *websErrorMsg(int code)
{
    WebsError   *ep;

    code &= WEBS_CODE_MASK;
    for (ep = websErrors; ep->code; ep++) {
        if (code == ep->code) {
            return ep->msg;
        }
    }
    return websErrorMsg(HTTP_CODE_INTERNAL_SERVER_ERROR);
}


/*
    Accessors
 */
PUBLIC char *websGetCookie(Webs *wp) { return wp->cookie; }
PUBLIC char *websGetExt(Webs *wp) { return wp->ext; }
PUBLIC char *websGetFilename(Webs *wp) { return wp->filename; }
PUBLIC char *websGetHost(Webs *wp) { return wp->host; }
PUBLIC char *websGetIfaddr(Webs *wp) { return wp->ifaddr; }
PUBLIC char *websGetIpaddr(Webs *wp) { return wp->ipaddr; }
PUBLIC char *websGetMethod(Webs *wp) { return wp->method; }
PUBLIC char *websGetPassword(Webs *wp) { return wp->password; }
PUBLIC char *websGetPath(Webs *wp) { return wp->path; }
PUBLIC int   websGetPort(Webs *wp) { return wp->port; }
PUBLIC char *websGetProtocol(Webs *wp) { return wp->protocol; }
PUBLIC char *websGetQuery(Webs *wp) { return wp->query; }
PUBLIC char *websGetServer() { return websHost; }
PUBLIC char *websGetServerAddress() { return websIpAddr; }
PUBLIC char *websGetServerAddressUrl() { return websIpAddrUrl; }
PUBLIC char *websGetServerUrl() { return websHostUrl; }
PUBLIC char *websGetUrl(Webs *wp) { return wp->url; }
PUBLIC char *websGetUserAgent(Webs *wp) { return wp->userAgent; }
PUBLIC char *websGetUsername(Webs *wp) { return wp->username; }


