#include "board_pinmux.h"
#include "pinctrl-machine.h"
#include "address_map.h"
#include "pinmux/pinmux.h"
#include "common.h"

// clang-format off
static struct pinctrl_machine_table osaka_ioc_table[] = {
	{ PAD_PWM0_IOMUX, PAD_PWM0_PUPD, PAD_PWM0_PCFG },
	{ PAD_PWM1_IOMUX, PAD_PWM1_PUPD, PAD_PWM1_PCFG },
	{ PAD_PWM3_IOMUX, PAD_PWM3_PUPD, PAD_PWM3_PCFG },
	{ PAD_UART1_TXD_IOMUX, PAD_UART1_TXD_PUPD, PAD_UART1_TXD_PCFG },
	{ PAD_UART1_RXD_IOMUX, PAD_UART1_RXD_PUPD, PAD_UART1_RXD_PCFG },
	{ PAD_SD0_CD_IOMUX, PAD_SD0_CD_PUPD, PAD_SD0_CD_PCFG },
	{ PAD_SD0_D2_IOMUX, PAD_SD0_D2_PUPD, PAD_SD0_D2_PCFG },
	{ PAD_SD0_D3_IOMUX, PAD_SD0_D3_PUPD, PAD_SD0_D3_PCFG },
	{ PAD_SD0_CMD_IOMUX, PAD_SD0_CMD_PUPD, PAD_SD0_CMD_PCFG },
	{ PAD_SD0_CK_IOMUX, PAD_SD0_CK_PUPD, PAD_SD0_CK_PCFG },
	{ PAD_SD0_D0_IOMUX, PAD_SD0_D0_PUPD, PAD_SD0_D0_PCFG },
	{ PAD_SD0_D1_IOMUX, PAD_SD0_D1_PUPD, PAD_SD0_D1_PCFG },
	{ PAD_QSPI_CE_N_IOMUX, PAD_QSPI_CE_N_PUPD, PAD_QSPI_CE_N_PCFG },
	{ PAD_QSPI_D1_IOMUX, PAD_QSPI_D1_PUPD, PAD_QSPI_D1_PCFG },
	{ PAD_QSPI_D2_IOMUX, PAD_QSPI_D2_PUPD, PAD_QSPI_D2_PCFG },
	{ PAD_QSPI_D3_IOMUX, PAD_QSPI_D3_PUPD, PAD_QSPI_D3_PCFG },
	{ PAD_QSPI_CK_IOMUX, PAD_QSPI_CK_PUPD, PAD_QSPI_CK_PCFG },
	{ PAD_QSPI_D0_IOMUX, PAD_QSPI_D0_PUPD, PAD_QSPI_D0_PCFG },
	{ PAD_EPHY_RST_IOMUX, PAD_EPHY_RST_PUPD, PAD_EPHY_RST_PCFG },
	{ PAD_EMAC_TX_CK_IOMUX, PAD_EMAC_TX_CK_PUPD, PAD_EMAC_TX_CK_PCFG },
	{ PAD_EMAC_TX_CTL_IOMUX, PAD_EMAC_TX_CTL_PUPD, PAD_EMAC_TX_CTL_PCFG },
	{ PAD_EMAC_TX_D1_IOMUX, PAD_EMAC_TX_D1_PUPD, PAD_EMAC_TX_D1_PCFG },
	{ PAD_EMAC_TX_D0_IOMUX, PAD_EMAC_TX_D0_PUPD, PAD_EMAC_TX_D0_PCFG },
	{ PAD_EMAC_RX_CK_IOMUX, PAD_EMAC_RX_CK_PUPD, PAD_EMAC_RX_CK_PCFG },
	{ PAD_EMAC_RX_D0_IOMUX, PAD_EMAC_RX_D0_PUPD, PAD_EMAC_RX_D0_PCFG },
	{ PAD_EMAC_RX_D1_IOMUX, PAD_EMAC_RX_D1_PUPD, PAD_EMAC_RX_D1_PCFG },
	{ PAD_EMAC_RX_CTL_IOMUX, PAD_EMAC_RX_CTL_PUPD, PAD_EMAC_RX_CTL_PCFG },
	{ PAD_EMAC_MDC_IOMUX, PAD_EMAC_MDC_PUPD, PAD_EMAC_MDC_PCFG },
	{ PAD_EMAC_MDIO_IOMUX, PAD_EMAC_MDIO_PUPD, PAD_EMAC_MDIO_PCFG },
	{ PAD_I2C2_SCL_IOMUX, PAD_I2C2_SCL_PUPD, PAD_I2C2_SCL_PCFG },
	{ PAD_I2C2_SDA_IOMUX, PAD_I2C2_SDA_PUPD, PAD_I2C2_SDA_PCFG },
	{ PAD_GPIO31_IOMUX, PAD_GPIO31_PUPD, PAD_GPIO31_PCFG },
	{ PAD_DVP_HSYNC_IOMUX, PAD_DVP_HSYNC_PUPD, PAD_DVP_HSYNC_PCFG },
	{ PAD_DVP_VSYNC_IOMUX, PAD_DVP_VSYNC_PUPD, PAD_DVP_VSYNC_PCFG },
	{ PAD_DVP_D7_IOMUX, PAD_DVP_D7_PUPD, PAD_DVP_D7_PCFG },
	{ PAD_DVP_D6_IOMUX, PAD_DVP_D6_PUPD, PAD_DVP_D6_PCFG },
	{ PAD_MIPI_SEL0_IOMUX, PAD_MIPI_SEL0_PUPD, PAD_MIPI_SEL0_PCFG },
	{ PAD_SENSOR_CLK_IOMUX, PAD_SENSOR_CLK_PUPD, PAD_SENSOR_CLK_PCFG },
	{ PAD_I2C0_SCL_IOMUX, PAD_I2C0_SCL_PUPD, PAD_I2C0_SCL_PCFG },
	{ PAD_I2C0_SDA_IOMUX, PAD_I2C0_SDA_PUPD, PAD_I2C0_SDA_PCFG },
	{ PAD_ADC_CH0_IOMUX, PAD_ADC_CH0_PUPD, PAD_ADC_CH0_PCFG },
	{ PAD_GPIO41_IOMUX, PAD_GPIO41_PUPD, PAD_GPIO41_PCFG },
	{ PAD_GPIO42_IOMUX, PAD_GPIO42_PUPD, PAD_GPIO42_PCFG },
	{ PAD_I2C1_SCL_IOMUX, PAD_I2C1_SCL_PUPD, PAD_I2C1_SCL_PCFG },
	{ PAD_I2C1_SDA_IOMUX, PAD_I2C1_SDA_PUPD, PAD_I2C1_SDA_PCFG },
	{ PAD_UART0_TXD_IOMUX, PAD_UART0_TXD_PUPD, PAD_UART0_TXD_PCFG },
	{ PAD_UART0_RXD_IOMUX, PAD_UART0_RXD_PUPD, PAD_UART0_RXD_PCFG },
	{ PAD_UART0_RTS_IOMUX, PAD_UART0_RTS_PUPD, PAD_UART0_RTS_PCFG },
	{ PAD_UART0_CTS_IOMUX, PAD_UART0_CTS_PUPD, PAD_UART0_CTS_PCFG },
};

// clang-format on

void pinmux_board_init(void)
{
	pinmux_init(osaka_ioc_table);
}
