#include "board_pinmux.h"
#include "pinctrl-machine.h"
#include "address_map.h"
#include "pinmux/pinmux.h"
#include "common.h"

// clang-format off
static struct pinctrl_machine_table sapporo_ioc_table[] = {
	{ PAD_GPIO_0_IOMUX, PAD_GPIO_0_PUPD, PAD_GPIO_0_PCFG },
	{ PAD_GPIO_1_IOMUX, PAD_GPIO_1_PUPD, PAD_GPIO_1_PCFG },
	{ PAD_GPIO_2_IOMUX, PAD_GPIO_2_PUPD, PAD_GPIO_2_PCFG },
	{ PAD_GPIO_3_IOMUX, PAD_GPIO_3_PUPD, PAD_GPIO_3_PCFG },
	{ PAD_GPIO_4_IOMUX, PAD_GPIO_4_PUPD, PAD_GPIO_4_PCFG },
	{ PAD_GPIO_5_IOMUX, PAD_GPIO_5_PUPD, PAD_GPIO_5_PCFG },
	{ PAD_GPIO_6_IOMUX, PAD_GPIO_6_PUPD, PAD_GPIO_6_PCFG },
	{ PAD_GPIO_7_IOMUX, PAD_GPIO_7_PUPD, PAD_GPIO_7_PCFG },
	{ PAD_GPIO_8_IOMUX, PAD_GPIO_8_PUPD, PAD_GPIO_8_PCFG },
	{ PAD_GPIO_9_IOMUX, PAD_GPIO_9_PUPD, PAD_GPIO_9_PCFG },
	{ PAD_GPIO_10_IOMUX, PAD_GPIO_10_PUPD, PAD_GPIO_10_PCFG },
	{ PAD_GPIO_11_IOMUX, PAD_GPIO_11_PUPD, PAD_GPIO_11_PCFG },
	{ PAD_GPIO_12_IOMUX, PAD_GPIO_12_PUPD, PAD_GPIO_12_PCFG },
	{ PAD_GPIO_13_IOMUX, PAD_GPIO_13_PUPD, PAD_GPIO_13_PCFG },
	{ PAD_GPIO_14_IOMUX, PAD_GPIO_14_PUPD, PAD_GPIO_14_PCFG },
	{ PAD_GPIO_15_IOMUX, PAD_GPIO_15_PUPD, PAD_GPIO_15_PCFG },
	{ PAD_GPIO_16_IOMUX, PAD_GPIO_16_PUPD, PAD_GPIO_16_PCFG },
	{ PAD_GPIO_17_IOMUX, PAD_GPIO_17_PUPD, PAD_GPIO_17_PCFG },
	{ PAD_GPIO_18_IOMUX, PAD_GPIO_18_PUPD, PAD_GPIO_18_PCFG },
	{ PAD_GPIO_19_IOMUX, PAD_GPIO_19_PUPD, PAD_GPIO_19_PCFG },
	{ PAD_GPIO_20_IOMUX, PAD_GPIO_20_PUPD, PAD_GPIO_20_PCFG },
	{ PAD_GPIO_21_IOMUX, PAD_GPIO_21_PUPD, PAD_GPIO_21_PCFG },
	{ PAD_GPIO_22_IOMUX, PAD_GPIO_22_PUPD, PAD_GPIO_22_PCFG },
	{ PAD_GPIO_23_IOMUX, PAD_GPIO_23_PUPD, PAD_GPIO_23_PCFG },
	{ PAD_GPIO_24_IOMUX, PAD_GPIO_24_PUPD, PAD_GPIO_24_PCFG },
	{ PAD_GPIO_25_IOMUX, PAD_GPIO_25_PUPD, PAD_GPIO_25_PCFG },
	{ PAD_GPIO_26_IOMUX, PAD_GPIO_26_PUPD, PAD_GPIO_26_PCFG },
	{ PAD_GPIO_27_IOMUX, PAD_GPIO_27_PUPD, PAD_GPIO_27_PCFG },
	{ PAD_GPIO_28_IOMUX, PAD_GPIO_28_PUPD, PAD_GPIO_28_PCFG },
	{ PAD_GPIO_29_IOMUX, PAD_GPIO_29_PUPD, PAD_GPIO_29_PCFG },
	{ PAD_GPIO_30_IOMUX, PAD_GPIO_30_PUPD, PAD_GPIO_30_PCFG },
	{ PAD_GPIO_31_IOMUX, PAD_GPIO_31_PUPD, PAD_GPIO_31_PCFG },
	{ PAD_GPIO_32_IOMUX, PAD_GPIO_32_PUPD, PAD_GPIO_32_PCFG },
	{ PAD_GPIO_33_IOMUX, PAD_GPIO_33_PUPD, PAD_GPIO_33_PCFG },
	{ PAD_GPIO_34_IOMUX, PAD_GPIO_34_PUPD, PAD_GPIO_34_PCFG },
	{ PAD_GPIO_35_IOMUX, PAD_GPIO_35_PUPD, PAD_GPIO_35_PCFG },
	{ PAD_GPIO_36_IOMUX, PAD_GPIO_36_PUPD, PAD_GPIO_36_PCFG },
	{ PAD_GPIO_37_IOMUX, PAD_GPIO_37_PUPD, PAD_GPIO_37_PCFG },
	{ PAD_GPIO_38_IOMUX, PAD_GPIO_38_PUPD, PAD_GPIO_38_PCFG },
	{ PAD_GPIO_39_IOMUX, PAD_GPIO_39_PUPD, PAD_GPIO_39_PCFG },
	{ PAD_GPIO_40_IOMUX, PAD_GPIO_40_PUPD, PAD_GPIO_40_PCFG },
	{ PAD_GPIO_41_IOMUX, PAD_GPIO_41_PUPD, PAD_GPIO_41_PCFG },
	{ PAD_GPIO_42_IOMUX, PAD_GPIO_42_PUPD, PAD_GPIO_42_PCFG },
	{ PAD_GPIO_43_IOMUX, PAD_GPIO_43_PUPD, PAD_GPIO_43_PCFG },
	{ PAD_GPIO_44_IOMUX, PAD_GPIO_44_PUPD, PAD_GPIO_44_PCFG },
	{ PAD_GPIO_45_IOMUX, PAD_GPIO_45_PUPD, PAD_GPIO_45_PCFG },
	{ PAD_GPIO_46_IOMUX, PAD_GPIO_46_PUPD, PAD_GPIO_46_PCFG },
	{ PAD_GPIO_47_IOMUX, PAD_GPIO_47_PUPD, PAD_GPIO_47_PCFG },
	{ PAD_GPIO_48_IOMUX, PAD_GPIO_48_PUPD, PAD_GPIO_48_PCFG },
	{ PAD_PMU_PWR_CTRL_IOMUX, PAD_PMU_PWR_CTRL_PUPD, PAD_PMU_PWR_CTRL_PCFG },
	{ PAD_PMU_WAKEUP_IOMUX, PAD_PMU_WAKEUP_PUPD, PAD_PMU_WAKEUP_PCFG },
	{ PAD_PMU_BUTTON_IOMUX, PAD_PMU_BUTTON_PUPD, PAD_PMU_BUTTON_PCFG },
};

// clang-format on

void pinmux_board_init(void)
{
	pinmux_init(sapporo_ioc_table);
}
