#!/bin/sh
#
# S23AGT300-28
#

case "$1" in
	start)
		#LED_R
		echo 0 > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio0/direction
		echo 0 > /sys/class/gpio/gpio0/value 

		#LED_B
		echo 1 > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio1/direction
		echo 0 > /sys/class/gpio/gpio1/value 

		#IR_LED_EN
		echo 2 > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio2/direction
		echo 0 > /sys/class/gpio/gpio2/value 

		#IR_CUT-A
		echo 12 > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio12/direction
		echo 0 > /sys/class/gpio/gpio12/value 

		#IR_CUT-B
		echo 14 > /sys/class/gpio/export
		echo "out" > /sys/class/gpio/gpio14/direction
		echo 0 > /sys/class/gpio/gpio14/value 

		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit $?

