#!/bin/sh

ALARMOUT_PIDFILE=/var/run/alarmoutd.pid
ALARMOUT_BIN=/system/bin/alarmoutd

start() {
	printf "Start alarmout daemon: "
	start-stop-daemon -S -m -b -p $ALARMOUT_PIDFILE \
		-x $ALARMOUT_BIN
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stop alarmout daemon: "
	start-stop-daemon -K -q -p $ALARMOUT_PIDFILE \
		-x $ALARMOUT_BIN
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?

