#!/bin/sh
#
# Start/stop av_main2 on AGT706-7
#

TZ=$(cat /etc/TZ)
export TZ

AV_MAIN2_BIN=/system/bin/av_main2
PIDFILE_AV_MAIN2=/var/run/av_main2.pid
RTSP_SERVER_BIN=""
PIDFILE_RTSP_SERVER_CH0=""
PIDFILE_RTSP_SERVER_CH1=""


do_start_rtsp_server() {
	local channel=$1
	eval pidfile=\$PIDFILE_RTSP_SERVER_CH${channel}
	echo "Starting RTSP Server Ch${channel} ..."

	start-stop-daemon --start --background --make-pidfile \
                        --pidfile "$pidfile" \
                        --exec "$RTSP_SERVER_BIN" \
                        -- $channel -S

	echo "Started RTSP Server Ch${channel}."
}

do_stop_rtsp_server() {
	local channel=$1
	eval pidfile=\$PIDFILE_RTSP_SERVER_CH${channel}
	start-stop-daemon -K -o -p $pidfile
        if [ $? = 1 ]; then
                echo "Failed to stop rtsp server ch$channel."
                exit 1
        fi
        if [ -f "$pidfile" ]; then
                PID=$(cat "$pidfile")
                while kill -0 "$PID" 2>/dev/null; do
                        sleep 1
            done
        else
                echo "PID file does not exist."
        fi

}

do_start_av_main2() {
	echo 3 > /proc/sys/kernel/printk
	sh /system/mpp/script/load_mpp.sh -i > /dev/null
	start-stop-daemon -S -m -b -x $AV_MAIN2_BIN -p $PIDFILE_AV_MAIN2
	if [ $? = 1 ]; then
		echo "Failed to start av_main2."
		exit 1
	fi
}

do_stop_av_main2() {
	start-stop-daemon -K -o -p $PIDFILE_AV_MAIN2
	if [ $? = 1 ]; then
		echo "Failed to stop av_main2."
		exit 1
	fi
	if [ -f "$PIDFILE_AV_MAIN2" ]; then
		PID=$(cat "$PIDFILE_AV_MAIN2")
		while kill -0 "$PID" 2>/dev/null; do
			sleep 1
	    done
	else
		echo "PID file does not exist."
	fi
	sh /system/mpp/script/load_mpp.sh -e
}

do_start() {
	echo "Starting av_main2..."
	do_start_av_main2
	sleep 1
}

do_stop() {
	printf "Stopping av_main2..."
	do_stop_av_main2
}

do_restart() {
	"$0" stop
	# wait for VB clean
	sleep 3
	"$0" start
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart|reload)
		do_restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
