#!/bin/sh
#
# Start/stop av_main2 for AGT804-42
#
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/root/bin:/system/bin
export TZ=$(cat /etc/TZ)


case "$1" in
  start)
    echo "Starting av_main2..."
    sh /system/mpp/script/load_mpp.sh -i

    echo g_rc_param=0,51,0,51,0,80,12,1000,100000,1,16,250000,24,0,0,30,2,48,32,4,0 > /dev/rc
    echo g_rgl_qp=2,60,2,60,0,0,45,8,2,6,300000,800000,500,3000,39,39,39,39,400000,800000,500,3000,0,0,0,0,20000000,20000000,4,100,300,0,0,-1 > /dev/enc

    echo nr_deghost_param=1,2,1,0,2,1,0,100,100,1,2,0,15,1,1,1,1,128,128,128,128,128,0,10,16,10,16 > /dev/isp
    echo enc_deghost_param=1,1,1,0,100,100,1,1,0,0,0,0,-10,-10,2,0,0 > /dev/enc

    echo g_stat_param=1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,20,50,128 > /dev/is
    echo minmax_ratio=16,16,12,10,8,7,6,6,6,5,5,4,4,3,3,2,2,1 > /dev/enc
    echo g_vbr_qp_table=36,35,34,33,32,30,20,16,14,12 > /dev/enc

    export DIP_INTL_INI_PATH=/system/mpp/script/dip_extend_day_agt800-38.ini
    export DIP_INTL_INI_TUNING=1

    av_main2 &
    ;;
  stop)
    printf "Stopping av_main2..."
    killall -s TERM av_main2
    ;;
  restart|reload)
    "$0" stop
    # wait for VB clean
    sleep 3
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac