#!/bin/sh
#
# Start/stop nginx
#
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/root/bin:/system/bin
export TZ=$(cat /usrdata/active_setting/TZ)

# RS_FPS_PRIORITY 0: RS FPS PRI LOW(default), 1: RS FPS PRI HIGH
export RS_FPS_PRIORITY=1

AV_MAIN2_BIN=/system/bin/av_main2
PIDFILE_AVMAIN=/var/run/av_main2.pid

case "$1" in
  start)
    echo "Starting av_main2..."
    sh /system/mpp/script/load_mpp.sh -i
    av_main2 &
    ;;
  stop)
    printf "Stopping av_main2..."
    killall -s TERM av_main2
    ;;
  restart|reload)
    "$0" stop
    echo "Starting av_main2..."
    "$0" stop
    # wait for VB clean
    sleep 3
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

