#!/bin/sh
#
# Start/stop av_main2
#
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/root/bin:/system/bin
export TZ=$(cat /usrdata/active_setting/TZ)

AV_MAIN2_BIN=/system/bin/av_main2
PIDFILE_AVMAIN=/var/run/av_main2.pid

case "$1" in
  start)
    echo 60 > /sys/class/gpio/export
    echo "out" > /sys/class/gpio/gpio60/direction
    echo 0 > /sys/class/gpio/gpio60/value 
    echo "Starting av_main2..."
    sh /system/mpp/script/load_mpp.sh -i
    echo g_vbr_qp_table=36,35,34,33,32,30,20,16,14,12 > /dev/enc
    echo g_rc_param=0,51,0,51,0,80,30,1000,100000,1,16,250000,24,0,0,30,2,48,35,4,0 > /dev/rc
    echo g_rgl_qp=2,60,2,60,0,0,45,8,2,6,300000,800000,500,3000,34,34,34,34,400000,800000,500,3000,0,0,0,0,20000000,20000000,4,100,300,0,0,-1 > /dev/enc
    echo nr_deghost_param=1,2,1,0,2,1,0,100,100,1,2,0,15,1,1,1,1,128,128,128,128,128,0,10,16,10,16 > /dev/isp
    echo enc_deghost_param=1,1,1,0,100,100,1,1,0,0,0,0,-10,-10,2,0,0 > /dev/enc
    echo g_stat_param=1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,20,50,128 > /dev/is
    export DIP_INTL_INI_PATH=/system/mpp/script/dip_extend_0.ini
    export DIP_INTL_INI_TUNING=1    
    start-stop-daemon -S -m -b -x $AV_MAIN2_BIN -p $PIDFILE_AVMAIN
    sleep 1
    ;;
  stop)
    printf "Stopping av_main2..."
    killall -s TERM av_main2
    ;;
  restart|reload)
    "$0" stop
    # wait for VB clean
    sleep 3
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

