#!/bin/sh

calib_country_c=/calib/factory_default/country_code
country_c=/usrdata/country_code
var="AU"

regrex='\(AF\|AL\|DZ\|AS\|AO\|AI\|AG\|AR\|AM\|AW\|AU\|AT\|AZ\|BS\|BH\|BD\|BY\|BE\|BZ\|BM\|BO\|BA\|BR\|BN\|BG\|KH\|CA\|KY\|CL\|CN\|CO\|CR\|HR\|CU\|CY\|CZ\|DK\|DO\|EC\|EG\|SV\|EE\|ET\|FI\|FR\|GF\|GE\|DE\|GR\|GL\|GD\|GU\|GT\|VA\|HN\|HK\|HU\|IS\|IN\|ID\|IR\|IQ\|IE\|IL\|IT\|JM\|JP\|JO\|KZ\|KE\|KP\|KR\|KW\|LA\|LV\|LB\|LS\|LI\|LT\|LU\|MO\|MK\|MW\|MY\|MV\|MT\|MH\|MR\|MU\|YT\|MX\|MD\|MC\|MN\|ME\|MA\|NP\|NL\|NZ\|NI\|NG\|NO\|OM\|PK\|PA\|PG\|PY\|PE\|PH\|PL\|PT\|PR\|QA\|RE\|RO\|RU\|BL\|SA\|SN\|RS\|SG\|SK\|SI\|ZA\|ES\|LK\|SD\|SE\|CH\|SY\|TW\|TH\|TT\|TN\|TR\|UG\|UA\|AE\|GB\|US\|UY\|UZ\|VE\|VN\|VI\|YE\|ZM\|ZW\)$'

set_var()
{
	length=${#var}
	if [ $length == 1 ]; then
		if [[ "$var" == "T" ]]; then
			var="TW"
			echo "TW" > $country_c
		elif [[ "$var" == "U" ]]; then
			var="US"
			echo "US" > $country_c
		elif [[ "$var" == "J" ]]; then
			var="JP"
			echo "JP" > $country_c
		else
			var="AU"
			echo "AU" > $country_c
		fi
	elif [ $length == 0 ]; then
		var="AU"
		echo "AU" > $country_c
	else
		if [[ $(expr match "$var" "$regrex") != 1 ]]; then
			echo "It is a valid country code..."
		else
			# reset country code
			var="AU"
			echo "AU" > $country_c
		fi
	fi
}

get_country_code()
{
	# check the country_code exist or not
	if [ -f "$country_c" ]; then
		echo "$country_c found"
		var="`cat $country_c`"
		set_var $var
	elif [ -f "$calib_country_c" ]; then
		echo "$calib_country_c found"
		var="`cat $calib_country_c`"
		set_var $var
	else
		var="AU"
		echo "Use default code $var"
		set_var $var
	fi

	if [[ "$var" == "JP" ]]; then
		echo "JP get !"
	elif [[ "$var" == "US" || "$var" == "TW" ]]; then
		echo "US or TW get !"
	else
		echo "Other get !"
	fi
}

get_reset_pin() {
	node_path=$(find /proc/device-tree/ -name "wifi-reset-pin")
	reset_pin=$(cat $node_path)
}

do_start() {
	get_reset_pin
	modprobe hichannel restart_script=/etc/init.d/factory/S41lpw
	ret=$?
	retry=0
	while [ $ret != 0 ] && [ $retry -lt 2 ]
	do
		echo $reset_pin > /sys/class/gpio/export
		echo "high" > /sys/class/gpio/gpio${reset_pin}/direction
		echo 0 > /sys/class/gpio/gpio${reset_pin}/value
		sleep 1
		echo 1 > /sys/class/gpio/gpio${reset_pin}/value
		echo "in" > /sys/class/gpio/gpio${reset_pin}/direction
		echo $reset_pin > /sys/class/gpio/unexport
		modprobe hichannel restart_script=/etc/init.d/factory/S41lpw
		ret=$?
		let retry=retry+1;
	done
	if [ $ret -eq 0 ]
	then
		get_country_code
		/usr/sbin/lpw_controller -c $var > /dev/console &
		/usr/sbin/lpw_supplicant > /dev/console &
		ifup wlan0
	else
		echo "[Error] load hichannel.ko fail"
	fi
}

do_recover() {
	sleep 1
	rmmod hichannel.ko
	echo 1 > /sys/class/gpio/gpio${reset_pin}/value
	echo "in" > /sys/class/gpio/gpio${reset_pin}/direction
	echo $reset_pin > /sys/class/gpio/unexport
	do_start
}

case "$1" in
	start)
		do_start &
		;;
	restart)
		# the following 2 lines are needed when restart is called by kernel module
		source /etc/profile
		get_reset_pin
		# terminate lpw_supplicant and lpw_controller
		ps | grep lpw_supplicant | grep -v grep | awk '{print $1}' | xargs kill
		ps | grep lpw_controller | grep -v grep | awk '{print $1}' | xargs kill
		# reset wifi module
		echo $reset_pin > /sys/class/gpio/export
		echo "high" > /sys/class/gpio/gpio${reset_pin}/direction
		echo 0 > /sys/class/gpio/gpio${reset_pin}/value
		# execute do_recover in background
		do_recover &
		;;
	stop)
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
esac

