#!/bin/sh
#
# sshd        Starts sshd.
#

SSH_KEY_PATH="/usrdata/active_setting/ssh"

# Make sure the ssh-keygen progam exists
[ -f /usr/bin/ssh-keygen ] || exit 0

# Create any missing keys
#/usr/bin/ssh-keygen -A

mkdir -p $SSH_KEY_PATH

if [ -e $SSH_KEY_PATH/ssh_host_rsa_key ]; then
	echo "ssh_host_rsa_key exists."
else
	/usr/bin/ssh-keygen -t rsa -b 1024 -C "" -P "" -f $SSH_KEY_PATH/ssh_host_rsa_key -q
fi

if [ -e $SSH_KEY_PATH/ssh_host_dsa_key ]; then
	echo "ssh_host_dsa_key exists."
else
	/usr/bin/ssh-keygen -t dsa -b 1024 -C "" -P "" -f $SSH_KEY_PATH/ssh_host_dsa_key -q
fi

if [ -e $SSH_KEY_PATH/ssh_host_ecdsa_key ]; then
	echo "ssh_host_ecdsa_key exists."
else
	/usr/bin/ssh-keygen -t ecdsa -b 521 -C "" -P "" -f $SSH_KEY_PATH/ssh_host_ecdsa_key -q
fi

if [ ! -e $SSH_KEY_PATH/ssh_host_ed25519_key ]; then
	echo "ssh_host_ed25519_key exists."
else
	/usr/bin/ssh-keygen -t ed25519 -b 1024 -C "" -P "" -f $SSH_KEY_PATH/ssh_host_ed25519_key -q
fi

umask 077

start() {

	# get Timezone
	export TZ=$(cat /etc/TZ)

	printf "Starting sshd: "
	/usr/sbin/sshd
	touch /var/lock/sshd
	echo "OK"
}
stop() {
	printf "Stopping sshd: "
	killall sshd
	rm -f /var/lock/sshd
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

