#! /bin/sh

NAME=sntp

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

#crond file path
path="/var/spool/cron/crontabs"

#Default time server IP
ip1="0.pool.ntp.org"

#SNTP_conf path
sntp_conf="/usrdata/active_setting/sntp.conf"

#timeMode_conf path
timeMode_conf="/usrdata/active_setting/timeMode.conf"

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
	start)

		# get Timezone
		export TZ=$(cat /etc/TZ)

		printf "Starting $NAME: "

		source "$timeMode_conf"
		if [ $Manual_enabled = 1 ]; then
			if [ -f "$path/root" ]; then
				sed -i '/sntp/d' $path/root
			fi
			echo "Enable Manual Sync."

		elif [ $Manual_enabled = 0  ]; then
			mkdir -p /var/db
			touch /var/db/ntp-kod

			#Get the sntp config
			source "$sntp_conf"
			$NAME -S "$NTP_server"
			day=$(($Interval / 24))
			hr=$(($Interval % 24))
			mkdir -p "$path"
			if [ $Interval -le 24 ]; then
				if [ -f "$path/root" ]; then
					sed -i '/sntp/d' $path/root
				fi
				if [ $day != 0 ]; then
				echo "0 0 * * * /usr/bin/sntp -S "$NTP_server" " >> "$path/root"
				[ $? = 0 ] && echo "OK" || echo "FAIL"
				echo "Interval update time was already set up."
				echo "Enable NTP Sync."

			elif [ $day = 0 ]; then
				echo "0 */$hr * * * /usr/bin/sntp -S "$NTP_server" " >> "$path/root"
				[ $? = 0 ] && echo "OK" || echo "FAIL"
				echo "Interval update time was already set up."
			fi

			elif [ $Interval -gt 24 ]; then
				echo "Interval update time should <= 24 hours."
				echo "Please try again..."
			fi
		fi
	;;
	stop)
		echo "Stopping $NAME: "
		sed -i '/sntp/d' $path/root
		echo "OK"
	;;
	restart|reload)
		echo "Restarting $NAME: "
		$0 stop
		sleep 1
		$0 start
	;;
	reset)
		echo "Reseting $NAME: "
		mkdir -p "$path"
		sed -i '/sntp/d' $path/root
		echo "0 8 * * * /usr/bin/sntp -S "$ip1" " >> "$path/root"
		[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|reset}" >&2
		exit 1
	;;
esac

exit 0
