#! /bin/sh

NAME=tuya_watchd
DAEMON=/usr/sbin/tuya_watchd

# Access mode
MODE=/system/bin/mode
# Production tool flag
run_prod_tool="/mnt/sdcard/RunProductionTool"

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
	start)

		# get Timezone
		export TZ=$(cat /etc/TZ)

		mode=$($MODE)
		# Production tool
		if [ -f $run_prod_tool ] && [ $mode == "user" ]; then
			echo " - Skip Tuya watchd..."
			return 0
		fi

		printf "Starting $NAME: "
		start-stop-daemon -S -b -x $DAEMON
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $NAME: "
		start-stop-daemon -K -q -x $DAEMON
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		echo "Restarting $NAME: "
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
