#!/bin/sh
#
# Start/stop eaif_server
#
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/root/bin:/system/bin

PIDFILE_MAIN=/var/run/eaif_server.pid

case "$1" in
  start)
    echo "Starting eaif_server..."
    /system/bin/eaif_server --config /system/eaif/config.ini --host 127.0.0.1 --port 8164 &
    ;;
  stop)
    printf "Stopping eaif_server..."
    killall -2 eaif_server
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

