#!/bin/sh
#
# Start/stop mpi_stream for AGT726-7
#
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/root/bin:/system/bin
export TZ=$(cat /etc/TZ)

do_video() {
	source /system/mpp/script/load_mpp.sh -i

	/system/bin/mpi_stream -d /system/mpp/case_config/DFN202-113002 > /dev/null &

	busybox modprobe audio_pcm.ko
	busybox modprobe audio_machine.ko

	echo 7 > /proc/sys/kernel/printk

	sleep 2
	od_demo -i /system/mpp/od_config/od_conf.json &

	sleep 2
	cmdsender --od 0 0 0 59 63 25 254 0 50 50 640 360 1

}

do_mmc() {
	# Load dw_mmc-host.ko if file does exist
	if [ -f /lib/modules/`uname -r`/kernel/drivers/mmc/host/dw_mmc-host.ko ]
	then
		modprobe dw_mmc-host
	fi

	# Load mmc_block.ko if file does exist
	if [ -f /lib/modules/`uname -r`/kernel/drivers/mmc/card/mmc_block.ko ]
	then
		modprobe mmc_block
	fi
}


case "$1" in
  start)
    do_video
    do_mmc
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
