#!/bin/sh

# auto_sensor_power_on.sh: Power on script to power up the sensor on DUT.
# This file is generated by codegen, DO NOT COMMIT THIS FILE.

SENSOR=GC4053

echo "Start to power on $SENSOR"

echo 49 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio49/direction

echo 0 > /sys/class/gpio/gpio49/value

usleep 1000

echo 1 > /sys/class/gpio/gpio49/value

usleep 4100

echo 49 > /sys/class/gpio/unexport

echo "Power on $SENSOR done"

