model_name=yolox
model_paths=fd.v1.0.1.ncnn
# inference type classify / detect / facereco / infer
inference_type=detect
# engine type armnn / tflite
# engine_type=tflite
# resolution=fix
width=320
height=192
channels=3
zeros=0
stds=1
input_int8_scale=0.499625
conf_thresh=0.1
iou_thresh=0.1
num_classes=1
labels=face
feature_output_pairs=3
num_anchors_per_feature=2
feature_stride=8,16,32
verbose=0
