# Copyright Augentix Inc. Proprietary and confidential.
# Unauthorized use or distribution is prohibited.
# Please contact customer.support@augentix.com for any inquiries.

# sensor_single.ini - MPI IQ files
# Usually provide some common or intuitive IQ settings.
# For more information, please refer to the documents about this file.

[DIP]
is_dip_en = 1
is_ae_en = 1
is_iso_en = 1
is_awb_en = 1
# ...

[AE]
frame_rate = 30
slow_frame_rate = 15
# ...
