# -------------------------------------------------------------------
# Shared caches(DL/SSTATE)
# -------------------------------------------------------------------
DL_DIR ?= "/work/yocto/cache/downloads"
SSTATE_DIR ?= "/work/yocto/cache/sstate-cache"

# -------------------------------------------------------------------
# Machine / distro
# -------------------------------------------------------------------
MACHINE ??= "qti-ipcam-cortexa7-soft"
DISTRO = "qti-ipcam"

# -------------------------------------------------------------------
# Parallelism
# -------------------------------------------------------------------
BB_NUMBER_THREADS ?= "16"
PARALLEL_MAKE ?= "-j16"

# -------------------------------------------------------------------
# Optional: reduce disk usage in early bring-up
# -------------------------------------------------------------------
INHERIT += "rm_work"

