#! /bin/sh

NAME=watchd
DAEMON=/usr/sbin/watchd

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
  start)
    printf "Starting $NAME: "
    start-stop-daemon -S -b -x $DAEMON
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  stop)
    ;;
  halt)
    printf "Stopping $NAME: "
    start-stop-daemon -K -q -x $DAEMON
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    printf "Stopping Watchdog: "
    echo 'V' > /dev/watchdog
    [ $? = 0 ] && echo "OK" || echo "FAIL"
    ;;
  restart|reload)
    echo "Restarting $NAME: "
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|halt|restart|reload}" >&2
    exit 1
    ;;
esac

exit 0
