#!/bin/sh -f
do_start() {
	# insert modules
	modprobe --dirname=/system -q pll
}

do_stop() {
	modprobe --dirname=/system -q pll
}

case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart|reload)
		do_stop
		do_start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
esac
