location = /cgi-bin/msg.cgi {
    root /system/www/;
    auth_basic "Please input password";
    auth_basic_user_file /etc/nginx/.htpasswd;
    expires -1;
    fastcgi_pass  127.0.0.1:9000;
}

location ~ \.cgi$ {
    root /system/www/;
    auth_basic "Please input password";
    auth_basic_user_file /etc/nginx/.htpasswd;
    expires -1;
    fastcgi_pass 127.0.0.1:9003;
    fastcgi_read_timeout 120s;
}
