/*
 * Copyright Augentix Inc. Proprietary and confidential.
 * Unauthorized use or distribution is prohibited.
 * Please contact customer.support@augentix.com for any inquiries.
 */

#include <kernel/pseudo_ta.h>
#include <tee_api_defines.h>
#include <drivers/spi/agtx_spi.h>
#include <drivers/spi/flash_protect.h>
#include <trace.h>
#include <drivers/agtx_mono_cnt.h>

/* UUID generated by uuidgen */
#define MONOTONIC_CNT_UUID                                             \
	{                                                              \
		0xfeb69b76, 0x8004, 0x4e54,                            \
		{                                                      \
			0xa7, 0x9f, 0xba, 0xb0, 0x0f, 0x98, 0x7a, 0x83 \
		}                                                      \
	}

#define MONOTONIC_CNT_NAME "monotonic_counter.pta"

static TEE_Result pta_cnt_get(uint32_t ptypes, TEE_Param params[TEE_NUM_PARAMS])
{
	/* Check params type:
	 * Params of get should contains the followings:
	 * ID: used to specify the cnt to be read
	 * Output value: value for returning cnt
	 */
	if (ptypes != TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_INPUT, TEE_PARAM_TYPE_VALUE_OUTPUT, TEE_PARAM_TYPE_NONE,
	                              TEE_PARAM_TYPE_NONE))
		return TEE_ERROR_BAD_PARAMETERS;

	if (params[0].value.a >= CFG_NUMBER_OF_CNTS) {
		EMSG("Attempt to get counter with unsupported counter type.");
		return TEE_ERROR_BAD_PARAMETERS;
	}

	/* Return the larger cnt */
	params[1].value.a = cnt_get(params[0].value.a);

	return TEE_SUCCESS;
}

static TEE_Result pta_shadow_cnt_set(uint32_t ptypes, TEE_Param params[TEE_NUM_PARAMS])
{
	/* Check params type:
	 * Params of get should contains the followings:
	 *   ID: used to specify the cnt to be read
	 *   Counter value
	 */
	if (ptypes != TEE_PARAM_TYPES(TEE_PARAM_TYPE_VALUE_INPUT, TEE_PARAM_TYPE_VALUE_INPUT, TEE_PARAM_TYPE_NONE,
	                              TEE_PARAM_TYPE_NONE))
		return TEE_ERROR_BAD_PARAMETERS;

	return cnt_set(params[0].value.a, params[1].value.a);
}

static TEE_Result pta_cnt_init(void)
{
	return cnt_init();
}
driver_init_late(pta_cnt_init);

static TEE_Result invoke_cmd(void *pSessionContext __unused, uint32_t cmd, uint32_t ptypes,
                             TEE_Param params[TEE_NUM_PARAMS])
{
	switch (cmd) {
	case PTA_CMD_CNT_GET:
		return pta_cnt_get(ptypes, params);
	case PTA_CMD_CNT_SET:
		return pta_shadow_cnt_set(ptypes, params);
	default:
		EMSG("Using undefined command\n");
		return TEE_ERROR_BAD_PARAMETERS;
	}
}

pseudo_ta_register(.uuid = MONOTONIC_CNT_UUID, .name = MONOTONIC_CNT_NAME, .flags = PTA_DEFAULT_FLAGS,
                   .invoke_command_entry_point = invoke_cmd);
