/*
 * Copyright Augentix Inc. Proprietary and confidential.
 * Unauthorized use or distribution is prohibited.
 * Please contact customer.support@augentix.com for any inquiries.
 */

#include <kernel/pseudo_ta.h>
#include <trace.h>
#include <drivers/agtx_se_sim.h>

/* UUID generated by uuidgen */
#define SE_SIM_UUID                                                    \
	{                                                              \
		0x21dbe80f, 0xc6ca, 0x49b5,                            \
		{                                                      \
			0x9a, 0x94, 0xde, 0x24, 0xd0, 0x4a, 0x81, 0xc4 \
		}                                                      \
	}

#define SE_SIM_NAME "se_sim.pta"

static TEE_Result pta_data_hmac_sha256(uint32_t ptypes, TEE_Param params[TEE_NUM_PARAMS])
{
	/* Check params type and size */
	if (ptypes != TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT, TEE_PARAM_TYPE_MEMREF_OUTPUT, TEE_PARAM_TYPE_NONE,
	                              TEE_PARAM_TYPE_NONE))
		return TEE_ERROR_BAD_PARAMETERS;

	uint8_t *data = params[0].memref.buffer;
	size_t data_sz = params[0].memref.size;
	uint8_t *hmac = params[1].memref.buffer;
	size_t hmac_sz = params[1].memref.size;

	if (!data || !hmac || data_sz == 0 || hmac_sz != SHA256_BYTE)
		return TEE_ERROR_BAD_PARAMETERS;

	/* Execute HMAC SHA256 */
	return data_hmac_sha256(data, hmac, data_sz, hmac_sz);
}

static TEE_Result pta_data_enc_aes_ecb_256_no_pad(uint32_t ptypes, TEE_Param params[TEE_NUM_PARAMS])
{
	/* Check params type and size */
	if (ptypes != TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT, TEE_PARAM_TYPE_MEMREF_OUTPUT, TEE_PARAM_TYPE_NONE,
	                              TEE_PARAM_TYPE_NONE))
		return TEE_ERROR_BAD_PARAMETERS;

	uint8_t *data = params[0].memref.buffer;
	size_t data_sz = params[0].memref.size;
	uint8_t *cipher = params[1].memref.buffer;
	size_t cipher_sz = params[1].memref.size;

	if (!data || !cipher || data_sz == 0 || cipher_sz != data_sz || (data_sz % AES_ECB_BLOCK_BYTE))
		return TEE_ERROR_BAD_PARAMETERS;

	/* Execute AES ECB 256 no pad encryption */
	return data_enc_aes_ecb_256_no_pad(data, cipher, data_sz, cipher_sz);
}

static TEE_Result pta_data_dec_aes_ecb_256_no_pad(uint32_t ptypes, TEE_Param params[TEE_NUM_PARAMS])
{
	/* Check params type and size */
	if (ptypes != TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT, TEE_PARAM_TYPE_MEMREF_OUTPUT, TEE_PARAM_TYPE_NONE,
	                              TEE_PARAM_TYPE_NONE))
		return TEE_ERROR_BAD_PARAMETERS;

	uint8_t *cipher = params[0].memref.buffer;
	size_t cipher_sz = params[0].memref.size;
	uint8_t *data = params[1].memref.buffer;
	size_t data_sz = params[1].memref.size;

	if (!cipher || !data || cipher_sz == 0 || cipher_sz != data_sz || (cipher_sz % AES_ECB_BLOCK_BYTE))
		return TEE_ERROR_BAD_PARAMETERS;

	/* Execute AES ECB 256 no pad decryption */
	return data_dec_aes_ecb_256_no_pad(cipher, data, cipher_sz, data_sz);
}

static TEE_Result pta_data_hkdf(uint32_t ptypes, TEE_Param params[TEE_NUM_PARAMS])
{
	/* Check params type and size */
	if (ptypes != TEE_PARAM_TYPES(TEE_PARAM_TYPE_MEMREF_INPUT, TEE_PARAM_TYPE_MEMREF_OUTPUT, TEE_PARAM_TYPE_NONE,
	                              TEE_PARAM_TYPE_NONE))
		return TEE_ERROR_BAD_PARAMETERS;

	uint8_t *salt = params[0].memref.buffer;
	size_t salt_sz = params[0].memref.size;
	uint8_t *okm = params[1].memref.buffer;
	size_t okm_sz = params[1].memref.size;

	if (!salt || !okm || salt_sz != SHA256_BYTE || okm_sz != SHA256_BYTE)
		return TEE_ERROR_BAD_PARAMETERS;

	/* Execute HKDF SHA256 */
	return hkdf_sha256(salt, salt_sz, okm, okm_sz);
}

static TEE_Result invoke_cmd(void *pSessionContext __unused, uint32_t cmd, uint32_t ptypes,
                             TEE_Param params[TEE_NUM_PARAMS])
{
	switch (cmd) {
	case PTA_CMD_DATA_HMAC_SHA256:
		return pta_data_hmac_sha256(ptypes, params);
	case PTA_CMD_DATA_ENC_AES_ECB_256_NO_PAD:
		return pta_data_enc_aes_ecb_256_no_pad(ptypes, params);
	case PTA_CMD_DATA_DEC_AES_ECB_256_NO_PAD:
		return pta_data_dec_aes_ecb_256_no_pad(ptypes, params);
	case PTA_CMD_DATA_HKDF:
		return pta_data_hkdf(ptypes, params);
	default:
		EMSG("Using undefined command\n");
		return TEE_ERROR_BAD_PARAMETERS;
	}
}

pseudo_ta_register(.uuid = SE_SIM_UUID, .name = SE_SIM_NAME, .flags = PTA_DEFAULT_FLAGS,
                   .invoke_command_entry_point = invoke_cmd);
