#! /bin/sh

NAME=crond
DAEMON=/usr/sbin/crond

# Gracefully exit if the package has been removed.
test -x $DAEMON || exit 0

# crond file path
path="/var/spool/cron/crontabs"

# Read config file if it is present.
if [ -r /etc/default/$NAME ]
then
  . /etc/default/$NAME
fi

case "$1" in
	start)

		# get Timezone
		export TZ=$(cat /etc/TZ)

		printf "Starting $NAME: "
		mkdir -p "$path"
		start-stop-daemon -S -q -x $DAEMON
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $NAME: "
		start-stop-daemon -K -q -n $NAME
		[ $? = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart|reload)
		echo "Restarting $NAME: "
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}" >&2
		exit 1
		;;
esac

exit 0
