pcm.asymed {
	type asym
	playback.pcm dmixer
	capture.pcm dsnooper
}
pcm.!default {
	type plug
	slave.pcm asymed
}
pcm.dsnooper {
	type dsnoop
	ipc_key 1025
	slave {
		pcm "hw:0,0"
		channels 1
		rate 8000
		period_size 1024
		buffer_size 4096
	}
}
pcm.dmixer {
	type dmix
	ipc_key 2050
	slave {
		pcm "hw:0,0"
		channels 1
		rate 8000
		period_size 1024
		buffer_size 4096
	}
}
