/*
 * Copyright Augentix Inc. Proprietary and confidential.
 * Unauthorized use or distribution is prohibited.
 * Please contact customer.support@augentix.com for any inquiries.
 */

#ifndef FPGA_PINMUX_H
#define FPGA_PINMUX_H

#ifndef __KERNEL__
#include <stdint.h>
#else
#include <linux/types.h>
#endif

#define FPGA_CONFIG_AMOUNT 41
#define FPGA_ROUTE_AMOUNT 27
#define FPGA_PINMUX_OFFS 0x4

//FPGA_CONFIG
#define FPGA_DBG0_IOSEL 0x1
#define FPGA_DBG1_IOSEL 0x1
#define FPGA_DBG2_IOSEL 0x1
#define FPGA_DBG3_IOSEL 0x0
#define FPGA_DBG4_IOSEL 0x0
#define FPGA_DBG5_IOSEL 0x0
#define FPGA_DBG6_IOSEL 0x0
#define FPGA_DBG7_IOSEL 0x0
#define FPGA_DBG8_IOSEL 0x0
#define FPGA_DBG9_IOSEL 0x1
#define FPGA_DBG10_IOSEL 0x1
#define FPGA_DBG11_IOSEL 0x1
#define FPGA_DBG12_IOSEL 0x1
#define ADAC_CLKI_SAADC_CH6 0x0
#define AADC_L_ENREFI_SAADCCS_CALN2 0x0
#define AADC_L_CHPAI_SAADCCS_SETN6 0x0
#define AADC_R_ENBIASI_SAADC_CH0 0x0
#define AADC_L_PH2DI_SAADCCS_SAMPLE 0x0
#define AADC_L_BGCHOPI_SAADCCS_SPWR 0x0
#define AADC_R_REFCHPAI_SAADC_VREFPSEL5 0x0
#define AADC_L_PH2I_SAADCCS_CK 0x0
#define AADC_R_ENBGPI_SAADC_CH1 0x0
#define AADC_R_PH1I_SAADC_VCMSEL3 0x0
#define AADC_L_ENBGPI_SAADCCS_CALP2 0x0
#define AADC_R_BGCHOPI_SAADC_CH2 0x0
#define AADC_L_ENBIASI_SAADCCS_CALP1 0x0
#define AADC_L_PH1DI_SAADCCS_CALN0 0x0
#define AADC_L_PH1I_SAADCCS_CALN1 0x0
#define AADC_R_PH2DI_SAADC_VCMSEL0 0x0
#define AADC_R_RESETBI_SAADCCS_VREFPSEL3 0x0
#define AADC_R_CHPAI_SAADC_VREFPSEL4 0x0
#define AADC_L_ENSDMI_SAADCCS_CALP0 0x0
#define AADC_L_REFCHPAI_SAADCCS_SETN7 0x0
#define AADC_R_ENSDMI_SAADC_VCMSEL5 0x0
#define AADC_R_SDMOI_SAADCCS_VREFPSEL2 0x0
#define ADAC_DINI_SAADC_CH7 0x0
#define AADC_R_PH1DI_SAADC_VCMSEL2 0x0
#define AADC_L_SDMO_SAADC_SETN4 0x0
#define AADC_R_ENREFI_SAADC_VCMSEL4 0x0
#define AADC_R_PH2I_SAADC_VCMSEL1 0x0
#define AADC_L_RSTB_SAADC_SETN5 0x0

//FPGA_ROUTE
#define PAD_SD_CD_ROUTE_SEL 0x0
#define PAD_SD_D0_ROUTE_SEL 0x0
#define PAD_SENSOR_CLK_ROUTE_SEL 0x1
#define PAD_SD_D2_ROUTE_SEL 0x0
#define PAD_SD_D3_ROUTE_SEL 0x0
#define PAD_SD_CK_ROUTE_SEL 0x0
#define PAD_SD_CMD_ROUTE_SEL 0x0
#define PAD_I2C0_SCL_ROUTE_SEL 0x1
#define PAD_I2C1_SCL_ROUTE_SEL 0x1
#define PAD_I2C0_SDA_ROUTE_SEL 0x1
#define PAD_I2C1_SDA_ROUTE_SEL 0x1
#define PAD_EMAC_RX_D0_ROUTE_SEL 0x0
#define PAD_EMAC_RX_D1_ROUTE_SEL 0x1
#define PAD_EMAC_TX_D1_ROUTE_SEL 0x1
#define PAD_EMAC_TX_D0_ROUTE_SEL 0x1
#define PAD_PWM3_ROUTE_SEL 0x0
#define PAD_PWM1_ROUTE_SEL 0x0
#define PAD_UART0_RTS_ROUTE_SEL 0x0
#define PAD_UART0_CTS_ROUTE_SEL 0x0
#define PAD_EPHY_RST_ROUTE_SEL 0x2
#define PAD_QSPI_CK_ROUTE_SEL 0x1
#define FPGA_I2C_SCL_ROUTE_SEL 0x0
#define FPGA_I2C_SDA_ROUTE_SEL 0x0
#define FPGA_UART2_TXD_ROUTE_SEL 0x1
#define FPGA_UART2_RXD_ROUTE_SEL 0x1
#define FPGA_UART2_CTS_ROUTE_SEL 0x1
#define FPGA_UART2_RTS_ROUTE_SEL 0x1

void fpga_pinmux_init(void);

#endif
